from __future__ import annotations

from typing import Any, Mapping, Protocol


class Cursor(Protocol):
    def execute(self, query: str, parameters: dict[str, object] | None = None) -> object: ...
    def fetchall(self) -> list[Mapping[str, Any]]: ...
    def fetchone(self) -> Mapping[str, Any] | None: ...


class Connection(Protocol):
    def cursor(self) -> Cursor: ...
    def commit(self) -> object: ...
    def rollback(self) -> object: ...


class Neo4jDriver(Protocol):
    def session(self, **kwargs: object) -> Any: ...
