"""update model raw body

Revision ID: 6470c51c78de
Revises: c7cdbd2ad62f
Create Date: 2026-01-17 02:00:05.242392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6470c51c78de'
down_revision: Union[str, None] = 'c7cdbd2ad62f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_body', sa.Column('body_hash', sa.String(length=64), nullable=False))
    op.drop_constraint(op.f('uq_raw_body_endpoint_content'), 'raw_body', type_='unique')
    op.create_unique_constraint('uq_raw_body_endpoint_hash', 'raw_body', ['endpoint_id', 'body_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_raw_body_endpoint_hash', 'raw_body', type_='unique')
    op.create_unique_constraint(op.f('uq_raw_body_endpoint_content'), 'raw_body', ['endpoint_id', 'body_content'], postgresql_nulls_not_distinct=False)
    op.drop_column('raw_body', 'body_hash')
    # ### end Alembic commands ###
