"""add action to scope_rules

Revision ID: 66a0fc812fd7
Revises: c5e0e949f274
Create Date: 2026-01-03 00:22:38.220353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66a0fc812fd7'
down_revision = '6470c51c78de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scope_rules', sa.Column('action', sa.String(length=10), server_default='include', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scope_rules', 'action')
    # ### end Alembic commands ###
