"""add asnmap tables

Revision ID: 69743ec8f89d
Revises: add_host_id_to_findings
Create Date: 2026-01-10 12:41:04.920816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69743ec8f89d'
down_revision = '66a0fc812fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_dns_records_host_id'), 'dns_records', ['host_id'], unique=False)
    op.create_index(op.f('ix_findings_host_id'), 'findings', ['host_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_host_id'), table_name='findings')
    op.drop_index(op.f('ix_dns_records_host_id'), table_name='dns_records')
    # ### end Alembic commands ###
