"""add unique constraint to leaks table

Revision ID: add05ecd6f2d
Revises: 66a0fc812fd7
Create Date: 2026-01-03 14:48:41.305897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add05ecd6f2d'
down_revision = '69743ec8f89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_leaks_program_id_content_endpoint_id', 'leaks', ['program_id', 'content', 'endpoint_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_leaks_program_id_content_endpoint_id', 'leaks', type_='unique')
    # ### end Alembic commands ###
