"""add new fields in service model

Revision ID: c7cdbd2ad62f
Revises: ab2eb207194a
Create Date: 2026-01-17 00:25:59.305491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7cdbd2ad62f'
down_revision: Union[str, None] = 'ab2eb207194a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_raw_body_endpoint_content', 'raw_body', ['endpoint_id', 'body_content'])
    op.add_column('services', sa.Column('favicon_hash', sa.String(length=20), nullable=True))
    op.add_column('services', sa.Column('websocket', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_services_favicon_hash'), 'services', ['favicon_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_favicon_hash'), table_name='services')
    op.drop_column('services', 'websocket')
    op.drop_column('services', 'favicon_hash')
    op.drop_constraint('uq_raw_body_endpoint_content', 'raw_body', type_='unique')
    # ### end Alembic commands ###
