"""Event type constants for EventBus messaging"""
from enum import Enum


class EventType(str, Enum):
    """Application event type constants for EventBus messaging"""

    SERVICE_EVENTS = "service_events"
    SUBDOMAIN_DISCOVERED = "subdomain_discovered"
    DNSX_FILTERED_HOSTS = "dnsx_filtered_hosts"
    SCAN_RESULTS_BATCH = "scan_results_batch"
    GAU_DISCOVERED = "gau_discovered"
    KATANA_RESULTS_BATCH = "katana_results_batch"
    HOST_DISCOVERED = "host_discovered"
    JS_FILES_DISCOVERED = "js_files_discovered"
    MANTRA_RESULTS_BATCH = "mantra_results_batch"
    FFUF_RESULTS_BATCH = "ffuf_results_batch"
    DNSX_BASIC_RESULTS_BATCH = "dnsx_basic_results_batch"
    DNSX_DEEP_RESULTS_BATCH = "dnsx_deep_results_batch"
    DNSX_PTR_RESULTS_BATCH = "dnsx_ptr_results_batch"
    CNAME_DISCOVERED = "cname_discovered"
    SUBJACK_RESULTS_BATCH = "subjack_results_batch"
    ASNMAP_RESULTS_BATCH = "asnmap_results_batch"
    ASN_DISCOVERED = "asn_discovered"
    CIDR_DISCOVERED = "cidr_discovered"
    IPS_EXPANDED = "ips_expanded"
    CIDR_SLICED = "cidr_sliced"
    IPS_AGGREGATED = "ips_aggregated"
    NAABU_RESULTS_BATCH = "naabu_results_batch"
    TLSX_RESULTS_BATCH = "tlsx_results_batch"
    CERT_SAN_DISCOVERED = "cert_san_discovered"
