import { 
  Search, Globe, Database, Network, FileCode, Bug, Shield 
} from 'lucide-react'
import { 
  scanSubfinder, scanHTTPX, scanGAU, scanWaymore, scanKatana,
  scanPlaywright, scanLinkFinder, scanMantra, scanFFUF, scanDNSx,
  scanSubjack, scanASNMap, scanMapCIDR, scanNaabu
} from '../services/api'

export const SCANS = [
  {
    id: 'subfinder',
    name: 'Subfinder',
    description: 'Subdomain enumeration',
    icon: Search,
    color: 'blue',
    api: scanSubfinder,
    form: 'Subfinder',
    initialValues: { targets: '', probe: true, timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'probe', label: 'Probe', type: 'checkbox' },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'httpx',
    name: 'HTTPX',
    description: 'HTTP probing',
    icon: Globe,
    color: 'green',
    api: scanHTTPX,
    form: 'HTTPX',
    initialValues: { targets: '', timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'gau',
    name: 'GAU',
    description: 'URL discovery from web archives',
    icon: Database,
    color: 'purple',
    api: scanGAU,
    form: 'GAU',
    initialValues: { targets: '', include_subs: true, timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'include_subs', label: 'Include Subdomains', type: 'checkbox' },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'waymore',
    name: 'Waymore',
    description: 'URL discovery from multiple sources',
    icon: Search,
    color: 'indigo',
    api: scanWaymore,
    form: 'Waymore',
    initialValues: { targets: '', timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'katana',
    name: 'Katana',
    description: 'Web crawling',
    icon: Network,
    color: 'red',
    api: scanKatana,
    form: 'Katana',
    initialValues: { targets: '', depth: 3, js_crawl: true, headless: false, timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'depth', label: 'Depth (1-10)', type: 'number', min: 1, max: 10 },
      { name: 'js_crawl', label: 'JS Crawl', type: 'checkbox' },
      { name: 'headless', label: 'Headless', type: 'checkbox' },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'playwright',
    name: 'Playwright',
    description: 'Interactive browser-based crawling',
    icon: Globe,
    color: 'pink',
    api: scanPlaywright,
    form: 'Playwright',
    initialValues: { targets: '', depth: 3, js_crawl: true, headless: false, timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'depth', label: 'Depth (1-10)', type: 'number', min: 1, max: 10 },
      { name: 'js_crawl', label: 'JS Crawl', type: 'checkbox' },
      { name: 'headless', label: 'Headless', type: 'checkbox' },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'linkfinder',
    name: 'LinkFinder',
    description: 'JS analysis for hidden endpoints',
    icon: FileCode,
    color: 'yellow',
    api: scanLinkFinder,
    form: 'LinkFinder',
    initialValues: { targets: '', timeout: 15 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 60 },
    ],
  },
  {
    id: 'mantra',
    name: 'Mantra',
    description: 'Secret scanning on JavaScript files',
    icon: Shield,
    color: 'orange',
    api: scanMantra,
    form: 'Mantra',
    initialValues: { targets: '', timeout: 300 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'ffuf',
    name: 'FFUF',
    description: 'Directory/file fuzzing',
    icon: Bug,
    color: 'cyan',
    api: scanFFUF,
    form: 'FFUF',
    initialValues: { targets: '', timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'dnsx',
    name: 'DNSx',
    description: 'DNS enumeration',
    icon: Network,
    color: 'teal',
    api: scanDNSx,
    form: 'DNSx',
    initialValues: { targets: '', mode: 'basic', timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'mode', label: 'Mode', type: 'select', options: ['basic', 'deep', 'ptr'] },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'subjack',
    name: 'Subjack',
    description: 'Subdomain takeover detection',
    icon: Shield,
    color: 'rose',
    api: scanSubjack,
    form: 'Subjack',
    initialValues: { targets: '', timeout: 300 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'asnmap',
    name: 'ASNMap',
    description: 'ASN/CIDR enumeration',
    icon: Network,
    color: 'violet',
    api: scanASNMap,
    form: 'ASNMap',
    initialValues: { targets: '', mode: 'domain', timeout: 300 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'mode', label: 'Mode', type: 'select', options: ['domain', 'asn', 'organization'] },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'mapcidr',
    name: 'MapCIDR',
    description: 'CIDR operations',
    icon: Database,
    color: 'slate',
    api: scanMapCIDR,
    form: 'MapCIDR',
    initialValues: { cidrs: '', operation: 'expand', count: '', host_count: '', skip_base: false, skip_broadcast: false, shuffle: false, timeout: 300 },
    fields: [
      { name: 'cidrs', label: 'CIDRs', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'operation', label: 'Operation', type: 'select', options: ['expand', 'slice_count', 'slice_host', 'aggregate'] },
      { name: 'count', label: 'Count (subnets)', type: 'number', min: 1, dependsOn: { field: 'operation', value: 'slice_count' } },
      { name: 'host_count', label: 'Host Count', type: 'number', min: 1, dependsOn: { field: 'operation', value: 'slice_host' } },
      { name: 'skip_base', label: 'Skip Base IPs (.0)', type: 'checkbox' },
      { name: 'skip_broadcast', label: 'Skip Broadcast IPs (.255)', type: 'checkbox' },
      { name: 'shuffle', label: 'Shuffle IPs', type: 'checkbox' },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'naabu',
    name: 'Naabu',
    description: 'Port scanning',
    icon: Network,
    color: 'amber',
    api: scanNaabu,
    form: 'Naabu',
    initialValues: { targets: '', scan_mode: 'active', ports: '', top_ports: '1000', rate: 1000, scan_type: 'c', exclude_cdn: true, nmap_cli: 'nmap -sV', timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'scan_mode', label: 'Scan Mode', type: 'select', options: ['active', 'passive', 'nmap'] },
      { name: 'ports', label: 'Ports', type: 'text', placeholder: '80,443,8080' },
      { name: 'top_ports', label: 'Top Ports', type: 'select', options: ['100', '1000', 'full'], dependsOn: { field: 'ports', value: '' } },
      { name: 'rate', label: 'Rate (pps)', type: 'number', min: 1, max: 10000 },
      { name: 'scan_type', label: 'Scan Type', type: 'select', options: ['s', 'c'] },
      { name: 'exclude_cdn', label: 'Exclude CDN/WAF', type: 'checkbox' },
      { name: 'nmap_cli', label: 'Nmap Command', type: 'text', placeholder: 'nmap -sV', dependsOn: { field: 'scan_mode', value: 'nmap' } },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
]
