import {
  scanSubfinder,
  scanHTTPX,
  scanGAU,
  scanWaymore,
  scanKatana,
  scanPlaywright,
  scanLinkFinder,
  scanMantra,
  scanFFUF,
  scanDNSx,
  scanSubjack,
  scanASNMap,
  scanMapCIDR,
  scanNaabu,
} from '@/services/api'

import {
  Search,
  Globe,
  Database,
  Network,
  FileCode,
  Bug,
  Shield,
} from 'lucide-react'

export const SCANS = [
  {
    id: 'subfinder',
    name: 'Subfinder',
    description: 'Subdomain enumeration',
    icon: Search,
    color: 'blue',
    api: scanSubfinder,
    form: 'Subfinder',
  },
  {
    id: 'httpx',
    name: 'HTTPX',
    description: 'HTTP probing',
    icon: Globe,
    color: 'green',
    api: scanHTTPX,
    form: 'HTTPX',
  },
  {
    id: 'gau',
    name: 'GAU',
    description: 'URL discovery from web archives',
    icon: Database,
    color: 'purple',
    api: scanGAU,
    form: 'GAU',
  },
  {
    id: 'waymore',
    name: 'Waymore',
    description: 'URL discovery from multiple sources',
    icon: Search,
    color: 'indigo',
    api: scanWaymore,
    form: 'Waymore',
  },
  {
    id: 'katana',
    name: 'Katana',
    description: 'Web crawling',
    icon: Network,
    color: 'red',
    api: scanKatana,
    form: 'Katana',
  },
  {
    id: 'playwright',
    name: 'Playwright',
    description: 'Interactive browser-based crawling',
    icon: Globe,
    color: 'pink',
    api: scanPlaywright,
    form: 'Playwright',
  },
  {
    id: 'linkfinder',
    name: 'LinkFinder',
    description: 'JS analysis for hidden endpoints',
    icon: FileCode,
    color: 'yellow',
    api: scanLinkFinder,
    form: 'LinkFinder',
  },
  {
    id: 'mantra',
    name: 'Mantra',
    description: 'Secret scanning in JS files',
    icon: Shield,
    color: 'orange',
    api: scanMantra,
    form: 'Mantra',
  },
  {
    id: 'ffuf',
    name: 'FFUF',
    description: 'Directory & file fuzzing',
    icon: Bug,
    color: 'cyan',
    api: scanFFUF,
    form: 'FFUF',
  },
  {
    id: 'dnsx',
    name: 'DNSx',
    description: 'DNS enumeration',
    icon: Network,
    color: 'teal',
    api: scanDNSx,
    form: 'DNSx',
  },
  {
    id: 'subjack',
    name: 'Subjack',
    description: 'Subdomain takeover detection',
    icon: Shield,
    color: 'rose',
    api: scanSubjack,
    form: 'Subjack',
  },
  {
    id: 'asnmap',
    name: 'ASNMap',
    description: 'ASN / CIDR enumeration',
    icon: Network,
    color: 'violet',
    api: scanASNMap,
    form: 'ASNMap',
  },
  {
    id: 'mapcidr',
    name: 'MapCIDR',
    description: 'CIDR operations',
    icon: Database,
    color: 'slate',
    api: scanMapCIDR,
    form: 'MapCIDR',
  },
  {
    id: 'naabu',
    name: 'Naabu',
    description: 'Port scanning',
    icon: Network,
    color: 'amber',
    api: scanNaabu,
    form: 'Naabu',
  },
]
