"""Action execution, run, outcome, and artifact tables."""
import uuid

from .base import (
    ArrayType,
    Boolean,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    JSONType,
    Integer,
    LargeBinary,
    String,
    Table,
    Text,
    UUID,
    UniqueConstraint,
    func,
    metadata,
    text,
)



jobs = Table(
    'jobs',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('action_id', UUID(), ForeignKey('action_requests.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('capability_id', String(100), nullable=False, index=True),
    Column('profile_id', String(100), nullable=False, index=True),
    Column('status', String(30), nullable=False, index=True),
    Column('correlation_id', UUID(), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index('idx_jobs_program_status', 'program_id', 'status'),
    CheckConstraint(
        "status IN ('queued', 'running', 'completed', 'failed', 'cancelled')",
        name='ck_jobs_status_valid'
    ),
)


runs = Table(
    'runs',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('job_id', UUID(), ForeignKey('jobs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('node_id', String(100), nullable=True, index=True),
    Column('event_name', String(150), nullable=True, index=True),
    Column('trigger_event_id', UUID(), nullable=True, index=True),
    Column('claim_key', String(64), nullable=True),
    Column('work_key', String(64), nullable=True),
    Column('coalesced_triggers', JSONType(), nullable=True),
    Column('coalesced_trigger_count', Integer, nullable=False, server_default="0"),
    Column('input_fingerprint', String(64), nullable=True, index=True),
    Column('target_fingerprint', String(64), nullable=True, index=True),
    Column('execution_mode', String(20), nullable=False, default='inline'),
    Column('status', String(30), nullable=False, index=True),
    Column('attempt', Integer, nullable=False, default=1),
    Column('leased_at', DateTime(timezone=True), nullable=True),
    Column('lease_owner', String(100), nullable=True),
    Column('lease_expires_at', DateTime(timezone=True), nullable=True),
    Column('started_at', DateTime(timezone=True), nullable=True),
    Column('scanner_started_at', DateTime(timezone=True), nullable=True),
    Column('flushing_at', DateTime(timezone=True), nullable=True),
    Column('next_run_at', DateTime(timezone=True), nullable=True),
    Column('target_count', Integer, nullable=True),
    Column('run_payload', JSONType(), nullable=True),
    Column('next_retry_at', DateTime(timezone=True), nullable=True, index=True),
    Column('finished_at', DateTime(timezone=True), nullable=True),
    Column('terminal_outcome', String(50), nullable=True, index=True),
    Column('retry_reason', String(100), nullable=True),
    Column('needs_reconcile', Boolean, nullable=False, default=False),
    Column('reconcile_reason', Text, nullable=True),
    Column('error', Text, nullable=True),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('claim_key', name='uq_runs_claim_key'),
    Index('idx_runs_program_status', 'program_id', 'status'),
    Index('idx_runs_node_event_created', 'node_id', 'event_name', 'created_at'),
    Index('idx_runs_execution_mode_status', 'execution_mode', 'status'),
    Index(
        'idx_runs_scheduled_active_work_key_unique',
        'work_key',
        unique=True,
        postgresql_where=text(
            "execution_mode = 'scheduled' "
            "AND work_key IS NOT NULL "
            "AND status IN ('queued', 'leased', 'running', 'flushing') "
            "AND terminal_outcome IS NULL"
        ),
    ),
    Index(
        'idx_runs_scheduled_work_lookup',
        'node_id',
        'program_id',
        'status',
        'work_key',
        postgresql_where=text(
            "execution_mode = 'scheduled' "
            "AND work_key IS NOT NULL"
        ),
    ),
    Index(
        'idx_runs_scheduled_ready_node_next_run_created',
        'node_id',
        'next_run_at',
        'created_at',
        'id',
        postgresql_where=text(
            "execution_mode = 'scheduled' "
            "AND status = 'queued' "
            "AND terminal_outcome IS NULL "
            "AND needs_reconcile = false"
        ),
    ),
    Index(
        'idx_runs_scheduled_lease_expiry',
        'lease_expires_at',
        'id',
        postgresql_where=text(
            "execution_mode = 'scheduled' "
            "AND status = 'leased'"
        ),
    ),
    CheckConstraint("attempt > 0", name='ck_runs_attempt_positive'),
    CheckConstraint(
        "claim_key IS NULL OR claim_key != ''",
        name='ck_runs_claim_key_not_empty',
    ),
    CheckConstraint(
        "work_key IS NULL OR work_key != ''",
        name='ck_runs_work_key_not_empty',
    ),
    CheckConstraint(
        "execution_mode IN ('inline', 'scheduled')",
        name='ck_runs_execution_mode_valid',
    ),
    CheckConstraint(
        "terminal_outcome IS NULL OR terminal_outcome IN "
        "('completed', 'partial', 'tool_failed', 'skipped', 'policy_blocked')",
        name='ck_runs_terminal_outcome_valid',
    ),
    CheckConstraint(
        "status IN ('queued', 'leased', 'running', 'flushing', 'completed', 'failed', 'dead', 'cancelled')",
        name='ck_runs_status_valid'
    ),
)


action_outcomes = Table(
    'action_outcomes',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('action_id', UUID(), ForeignKey('action_requests.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('job_id', UUID(), ForeignKey('jobs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('run_id', UUID(), ForeignKey('runs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('capability_id', String(100), nullable=False, index=True),
    Column('profile_id', String(100), nullable=False, index=True),
    Column('node_id', String(100), nullable=True, index=True),
    Column('event_name', String(150), nullable=True, index=True),
    Column('correlation_id', UUID(), nullable=True, index=True),
    Column('status', String(30), nullable=False, index=True),
    Column('terminal_outcome', String(50), nullable=True, index=True),
    Column('attempt', Integer, nullable=False),
    Column('target_count', Integer, nullable=True),
    Column('started_at', DateTime(timezone=True), nullable=True),
    Column('finished_at', DateTime(timezone=True), nullable=True),
    Column('duration_ms', Integer, nullable=True),
    Column('error_count', Integer, nullable=False, default=0),
    Column('error_message', Text, nullable=True),
    Column('raw_artifact_count', Integer, nullable=False, default=0),
    Column('raw_artifact_bytes', Integer, nullable=False, default=0),
    Column('observed_hosts_count', Integer, nullable=False, default=0),
    Column('observed_services_count', Integer, nullable=False, default=0),
    Column('observed_endpoints_count', Integer, nullable=False, default=0),
    Column('http_observation_count', Integer, nullable=False, default=0),
    Column('javascript_reference_count', Integer, nullable=False, default=0),
    Column('new_hosts_count', Integer, nullable=True),
    Column('new_services_count', Integer, nullable=True),
    Column('new_endpoints_count', Integer, nullable=True),
    Column('before_surface_snapshot_id', UUID(), nullable=True),
    Column('after_surface_snapshot_id', UUID(), nullable=True),
    Column('new_surface_nodes_count', Integer, nullable=True),
    Column('new_surface_edges_count', Integer, nullable=True),
    Column('new_surface_clusters_count', Integer, nullable=True),
    Column('new_surface_deltas_count', Integer, nullable=True),
    Column('new_graph_facts_count', Integer, nullable=True),
    Column('new_search_documents_count', Integer, nullable=True),
    Column('manual_interest', Boolean, nullable=True),
    Column('manual_stop', Boolean, nullable=True),
    Column('continued_by_followup', Boolean, nullable=True),
    Column('report_created', Boolean, nullable=True),
    Column('triage_outcome', String(100), nullable=True),
    Column('information_gain_score', Float, nullable=False, default=0.0),
    Column('score_version', String(100), nullable=False),
    Column('score_breakdown', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('run_id', name='uq_action_outcomes_run_id'),
    Index('idx_action_outcomes_program_score', 'program_id', 'information_gain_score'),
    Index('idx_action_outcomes_campaign_created', 'campaign_id', 'created_at'),
    Index('idx_action_outcomes_capability_profile', 'capability_id', 'profile_id'),
    CheckConstraint("capability_id != ''", name='ck_action_outcomes_capability_not_empty'),
    CheckConstraint("profile_id != ''", name='ck_action_outcomes_profile_not_empty'),
    CheckConstraint("attempt > 0", name='ck_action_outcomes_attempt_positive'),
    CheckConstraint("target_count IS NULL OR target_count >= 0", name='ck_action_outcomes_target_count_nonnegative'),
    CheckConstraint("duration_ms IS NULL OR duration_ms >= 0", name='ck_action_outcomes_duration_nonnegative'),
    CheckConstraint("error_count >= 0", name='ck_action_outcomes_error_count_nonnegative'),
    CheckConstraint("raw_artifact_count >= 0", name='ck_action_outcomes_raw_artifact_count_nonnegative'),
    CheckConstraint("raw_artifact_bytes >= 0", name='ck_action_outcomes_raw_artifact_bytes_nonnegative'),
    CheckConstraint("observed_hosts_count >= 0", name='ck_action_outcomes_observed_hosts_nonnegative'),
    CheckConstraint("observed_services_count >= 0", name='ck_action_outcomes_observed_services_nonnegative'),
    CheckConstraint("observed_endpoints_count >= 0", name='ck_action_outcomes_observed_endpoints_nonnegative'),
    CheckConstraint("http_observation_count >= 0", name='ck_action_outcomes_http_observation_nonnegative'),
    CheckConstraint("javascript_reference_count >= 0", name='ck_action_outcomes_javascript_reference_nonnegative'),
    CheckConstraint("new_hosts_count IS NULL OR new_hosts_count >= 0", name='ck_action_outcomes_new_hosts_nonnegative'),
    CheckConstraint("new_services_count IS NULL OR new_services_count >= 0", name='ck_action_outcomes_new_services_nonnegative'),
    CheckConstraint("new_endpoints_count IS NULL OR new_endpoints_count >= 0", name='ck_action_outcomes_new_endpoints_nonnegative'),
    CheckConstraint("new_surface_nodes_count IS NULL OR new_surface_nodes_count >= 0", name='ck_action_outcomes_surface_nodes_nonnegative'),
    CheckConstraint("new_surface_edges_count IS NULL OR new_surface_edges_count >= 0", name='ck_action_outcomes_surface_edges_nonnegative'),
    CheckConstraint("new_surface_clusters_count IS NULL OR new_surface_clusters_count >= 0", name='ck_action_outcomes_surface_clusters_nonnegative'),
    CheckConstraint("new_surface_deltas_count IS NULL OR new_surface_deltas_count >= 0", name='ck_action_outcomes_surface_deltas_nonnegative'),
    CheckConstraint("new_graph_facts_count IS NULL OR new_graph_facts_count >= 0", name='ck_action_outcomes_graph_facts_nonnegative'),
    CheckConstraint("new_search_documents_count IS NULL OR new_search_documents_count >= 0", name='ck_action_outcomes_search_documents_nonnegative'),
    CheckConstraint("information_gain_score >= 0", name='ck_action_outcomes_score_nonnegative'),
    CheckConstraint("score_version != ''", name='ck_action_outcomes_score_version_not_empty'),
    CheckConstraint(
        "status IN ('queued', 'leased', 'running', 'flushing', 'completed', 'failed', 'dead', 'cancelled')",
        name='ck_action_outcomes_status_valid',
    ),
    CheckConstraint(
        "terminal_outcome IS NULL OR terminal_outcome IN "
        "('completed', 'partial', 'tool_failed', 'skipped', 'policy_blocked')",
        name='ck_action_outcomes_terminal_outcome_valid',
    ),
)


action_outcome_feedback_events = Table(
    'action_outcome_feedback_events',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('outcome_id', UUID(), ForeignKey('action_outcomes.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('action_id', UUID(), ForeignKey('action_requests.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('job_id', UUID(), ForeignKey('jobs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('run_id', UUID(), ForeignKey('runs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('manual_interest', Boolean, nullable=True),
    Column('manual_stop', Boolean, nullable=True),
    Column('continued_by_followup', Boolean, nullable=True),
    Column('report_created', Boolean, nullable=True),
    Column('triage_outcome', String(100), nullable=True),
    Column('actor', String(150), nullable=False),
    Column('source', String(100), nullable=False),
    Column('reason', Text, nullable=True),
    Column('confidence', Float, nullable=False, default=0.5),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index('idx_action_outcome_feedback_action_created', 'action_id', 'created_at'),
    Index('idx_action_outcome_feedback_run_created', 'run_id', 'created_at'),
    Index('idx_action_outcome_feedback_outcome_created', 'outcome_id', 'created_at'),
    CheckConstraint("actor != ''", name='ck_action_outcome_feedback_actor_not_empty'),
    CheckConstraint("source != ''", name='ck_action_outcome_feedback_source_not_empty'),
    CheckConstraint(
        "confidence >= 0 AND confidence <= 1",
        name='ck_action_outcome_feedback_confidence_range',
    ),
    CheckConstraint(
        "manual_interest IS NOT NULL OR manual_stop IS NOT NULL OR "
        "continued_by_followup IS NOT NULL OR report_created IS NOT NULL OR "
        "triage_outcome IS NOT NULL",
        name='ck_action_outcome_feedback_has_signal',
    ),
    CheckConstraint(
        "triage_outcome IS NULL OR triage_outcome != ''",
        name='ck_action_outcome_feedback_triage_not_empty',
    ),
)


action_experience_proposal_runs = Table(
    'action_experience_proposal_runs',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('source_outcome_id', UUID(), ForeignKey('action_outcomes.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('source_action_id', UUID(), ForeignKey('action_requests.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('source_job_id', UUID(), ForeignKey('jobs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('source_run_id', UUID(), ForeignKey('runs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('status', String(30), nullable=False),
    Column('candidate_count', Integer, nullable=False, default=0),
    Column('feature_builder_version', String(100), nullable=False),
    Column('feature_keys', JSONType(), nullable=False, default=list),
    Column('graph_counts', JSONType(), nullable=False, default=dict),
    Column('error', Text, nullable=True),
    Column('produced_by', String(100), nullable=False, server_default='action-experience-proposal-worker'),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('source_outcome_id', name='uq_action_experience_proposal_runs_source'),
    Index('idx_action_experience_proposal_runs_status_created', 'status', 'created_at'),
    CheckConstraint(
        "status IN ('completed', 'no_candidates', 'failed')",
        name='ck_action_experience_proposal_runs_status_valid',
    ),
    CheckConstraint(
        "candidate_count >= 0",
        name='ck_action_experience_proposal_runs_candidate_count_nonnegative',
    ),
    CheckConstraint(
        "feature_builder_version != ''",
        name='ck_action_experience_proposal_runs_builder_not_empty',
    ),
    CheckConstraint("produced_by != ''", name='ck_action_experience_proposal_runs_producer_not_empty'),
)


action_experience_proposals = Table(
    'action_experience_proposals',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('proposal_run_id', UUID(), ForeignKey('action_experience_proposal_runs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('source_outcome_id', UUID(), ForeignKey('action_outcomes.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('source_action_id', UUID(), ForeignKey('action_requests.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('source_job_id', UUID(), ForeignKey('jobs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('source_run_id', UUID(), ForeignKey('runs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('proposal_key', String(300), nullable=False),
    Column('status', String(30), nullable=False, server_default='pending', index=True),
    Column('rank', Integer, nullable=False),
    Column('capability_id', String(100), nullable=False, index=True),
    Column('profile_id', String(100), nullable=False, index=True),
    Column('utility_score', Float, nullable=False, default=0.0),
    Column('sample_count', Integer, nullable=False, default=0),
    Column('avg_similarity', Float, nullable=False, default=0.0),
    Column('avg_information_gain_score', Float, nullable=False, default=0.0),
    Column('human_positive_rate', Float, nullable=False, default=0.0),
    Column('human_stop_rate', Float, nullable=False, default=0.0),
    Column('explanation', JSONType(), nullable=False, default=dict),
    Column('produced_by', String(100), nullable=False, server_default='action-experience-proposal-worker'),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('proposal_key', name='uq_action_experience_proposals_key'),
    Index('idx_action_experience_proposals_pending_program_rank', 'program_id', 'status', 'rank', 'created_at'),
    Index('idx_action_experience_proposals_campaign_status', 'campaign_id', 'status', 'utility_score'),
    Index('idx_action_experience_proposals_capability_profile', 'capability_id', 'profile_id'),
    CheckConstraint("proposal_key != ''", name='ck_action_experience_proposals_key_not_empty'),
    CheckConstraint(
        "status IN ('pending', 'accepting', 'accepted', 'accept_failed', 'rejected', 'suppressed', 'expired')",
        name='ck_action_experience_proposals_status_valid',
    ),
    CheckConstraint("rank > 0", name='ck_action_experience_proposals_rank_positive'),
    CheckConstraint("capability_id != ''", name='ck_action_experience_proposals_capability_not_empty'),
    CheckConstraint("profile_id != ''", name='ck_action_experience_proposals_profile_not_empty'),
    CheckConstraint("utility_score >= 0", name='ck_action_experience_proposals_utility_nonnegative'),
    CheckConstraint("sample_count >= 0", name='ck_action_experience_proposals_sample_count_nonnegative'),
    CheckConstraint("avg_similarity >= 0 AND avg_similarity <= 1", name='ck_action_experience_proposals_similarity_range'),
    CheckConstraint(
        "human_positive_rate >= 0 AND human_positive_rate <= 1",
        name='ck_action_experience_proposals_positive_rate_range',
    ),
    CheckConstraint(
        "human_stop_rate >= 0 AND human_stop_rate <= 1",
        name='ck_action_experience_proposals_stop_rate_range',
    ),
    CheckConstraint("produced_by != ''", name='ck_action_experience_proposals_producer_not_empty'),
)


raw_artifacts = Table(
    'raw_artifacts',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('job_id', UUID(), nullable=True, index=True),
    Column('run_id', UUID(), nullable=True, index=True),
    Column('node_id', String(100), nullable=False, index=True),
    Column('event_name', String(150), nullable=False, index=True),
    Column('artifact_type', String(50), nullable=False),
    Column('storage_uri', Text, nullable=False),
    Column('sha256', String(64), nullable=False),
    Column('size_bytes', Integer, nullable=False),
    Column('storage_size_bytes', Integer, nullable=False, server_default='0'),
    Column('content_encoding', String(20), nullable=False, server_default='identity'),
    Column('retention_class', String(30), nullable=False, server_default='program_lifetime'),
    Column('preview', Text, nullable=True),
    Column('sanitized_preview', Text, nullable=True),
    Column('sanitizer_version', String(100), nullable=True),
    Column('redaction_policy_version', String(100), nullable=True),
    Column('raw_safe_for_llm', Boolean, nullable=False, server_default='false'),
    Column('sanitized_safe_for_llm', Boolean, nullable=False, server_default='false'),
    Column('parser_name', String(150), nullable=False, server_default='unknown'),
    Column('parser_version', String(100), nullable=False, server_default='1'),
    Column(
        'scope_decision_id',
        UUID(),
        ForeignKey('scope_decisions.id', ondelete='SET NULL'),
        nullable=True,
        index=True,
    ),
    Column(
        'source_targets',
        JSONType(),
        nullable=False,
        default=list,
        server_default=text("'[]'"),
    ),
    Column(
        'parent_artifact_id',
        UUID(),
        ForeignKey('raw_artifacts.id', ondelete='SET NULL'),
        nullable=True,
        index=True,
    ),
    Column('artifact_metadata', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index('idx_raw_artifacts_program_created', 'program_id', 'created_at'),
    Index('idx_raw_artifacts_run', 'run_id'),
    Index('idx_raw_artifacts_retention_class', 'retention_class'),
    CheckConstraint("artifact_type != ''", name='ck_raw_artifacts_type_not_empty'),
    CheckConstraint("storage_uri != ''", name='ck_raw_artifacts_storage_uri_not_empty'),
    CheckConstraint("size_bytes >= 0", name='ck_raw_artifacts_size_non_negative'),
    CheckConstraint(
        "storage_size_bytes >= 0",
        name='ck_raw_artifacts_storage_size_non_negative',
    ),
    CheckConstraint(
        "content_encoding IN ('identity', 'gzip')",
        name='ck_raw_artifacts_content_encoding_valid',
    ),
    CheckConstraint(
        "retention_class IN ('ephemeral', 'short_lived', 'program_lifetime', 'legal_hold')",
        name='ck_raw_artifacts_retention_class_valid',
    ),
    CheckConstraint(
        (
            "sanitized_safe_for_llm = false OR "
            "(sanitized_preview IS NOT NULL "
            "AND sanitizer_version IS NOT NULL "
            "AND redaction_policy_version IS NOT NULL)"
        ),
        name='ck_raw_artifacts_sanitized_llm_requires_preview',
    ),
    CheckConstraint(
        "parser_name != ''",
        name='ck_raw_artifacts_parser_name_not_empty',
    ),
    CheckConstraint(
        "parser_version != ''",
        name='ck_raw_artifacts_parser_version_not_empty',
    ),
)
