"""Credential registry tables."""
import uuid

from .base import (
    ArrayType,
    Boolean,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    JSONType,
    Integer,
    LargeBinary,
    String,
    Table,
    Text,
    UUID,
    UniqueConstraint,
    func,
    metadata,
    text,
)



credential_refs = Table(
    'credential_refs',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('credential_ref', String(255), nullable=False),
    Column('identity_label', String(150), nullable=False),
    Column('secret_kind', String(50), nullable=False),
    Column('scope_json', JSONType(), nullable=False, default=dict),
    Column('status', String(30), nullable=False, default='active', index=True),
    Column('expires_at', DateTime(timezone=True), nullable=True),
    Column('current_secret_version_id', UUID(), ForeignKey('credential_secret_versions.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('refresh_policy_json', JSONType(), nullable=False, default=dict),
    Column('refresh_status', String(30), nullable=False, default='not_configured', index=True),
    Column('last_refreshed_at', DateTime(timezone=True), nullable=True),
    Column('next_refresh_at', DateTime(timezone=True), nullable=True, index=True),
    Column('metadata_json', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('program_id', 'credential_ref', name='uq_credential_refs_program_ref'),
    Index('idx_credential_refs_program_identity', 'program_id', 'identity_label'),
    Index('idx_credential_refs_program_status', 'program_id', 'status'),
    Index('idx_credential_refs_program_refresh', 'program_id', 'refresh_status', 'next_refresh_at'),
    CheckConstraint("credential_ref LIKE 'credref:%'", name='ck_credential_refs_ref_prefix'),
    CheckConstraint("identity_label != ''", name='ck_credential_refs_identity_not_empty'),
    CheckConstraint("secret_kind != ''", name='ck_credential_refs_secret_kind_not_empty'),
    CheckConstraint(
        "status IN ('active', 'disabled', 'revoked')",
        name='ck_credential_refs_status_valid',
    ),
    CheckConstraint(
        "refresh_status IN ('not_configured', 'fresh', 'refresh_due', 'refresh_failed', 'disabled')",
        name='ck_credential_refs_refresh_status_valid',
    ),
)


credential_secret_versions = Table(
    'credential_secret_versions',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('credential_ref_id', UUID(), ForeignKey('credential_refs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('version', Integer, nullable=False),
    Column('secret_kind', String(50), nullable=False),
    Column('storage_backend', String(80), nullable=False),
    Column('ciphertext', LargeBinary(), nullable=True),
    Column('nonce', LargeBinary(), nullable=True),
    Column('key_id', String(120), nullable=True),
    Column('external_secret_ref', String(500), nullable=True),
    Column('status', String(30), nullable=False, default='active', index=True),
    Column('expires_at', DateTime(timezone=True), nullable=True, index=True),
    Column('replaced_by_version_id', UUID(), ForeignKey('credential_secret_versions.id', ondelete='SET NULL'), nullable=True),
    Column('metadata_json', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('credential_ref_id', 'version', name='uq_credential_secret_versions_ref_version'),
    Index('idx_credential_secret_versions_ref_status', 'credential_ref_id', 'status'),
    CheckConstraint("version > 0", name='ck_credential_secret_versions_version_positive'),
    CheckConstraint("secret_kind != ''", name='ck_credential_secret_versions_kind_not_empty'),
    CheckConstraint("storage_backend != ''", name='ck_credential_secret_versions_backend_not_empty'),
    CheckConstraint(
        "status IN ('active', 'retired', 'expired', 'revoked')",
        name='ck_credential_secret_versions_status_valid',
    ),
    CheckConstraint(
        "replaced_by_version_id IS NULL OR replaced_by_version_id != id",
        name='ck_credential_secret_versions_not_self_replaced',
    ),
    CheckConstraint(
        "ciphertext IS NOT NULL OR external_secret_ref IS NOT NULL",
        name='ck_credential_secret_versions_has_secret_pointer',
    ),
)


credential_leases = Table(
    'credential_leases',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('credential_ref_id', UUID(), ForeignKey('credential_refs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('secret_version_id', UUID(), ForeignKey('credential_secret_versions.id', ondelete='RESTRICT'), nullable=False, index=True),
    Column('purpose', String(120), nullable=False),
    Column('capability', String(120), nullable=False),
    Column('target_scope', String(500), nullable=False),
    Column('auth_injection_json', JSONType(), nullable=False, default=dict),
    Column('status', String(30), nullable=False, default='issued', index=True),
    Column('issued_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('expires_at', DateTime(timezone=True), nullable=False, index=True),
    Column('revoked_at', DateTime(timezone=True), nullable=True),
    Column('audit_json', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index('idx_credential_leases_program_status_expires', 'program_id', 'status', 'expires_at'),
    Index('idx_credential_leases_ref_status', 'credential_ref_id', 'status'),
    CheckConstraint("purpose != ''", name='ck_credential_leases_purpose_not_empty'),
    CheckConstraint("capability != ''", name='ck_credential_leases_capability_not_empty'),
    CheckConstraint("target_scope != ''", name='ck_credential_leases_target_scope_not_empty'),
    CheckConstraint(
        "status IN ('issued', 'used', 'expired', 'revoked')",
        name='ck_credential_leases_status_valid',
    ),
    CheckConstraint("expires_at > issued_at", name='ck_credential_leases_expires_after_issued'),
)
