"""Graph projection queue, audit, fact batch, and watermark tables."""
import uuid

from .base import (
    ArrayType,
    Boolean,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    JSONType,
    Integer,
    LargeBinary,
    String,
    Table,
    Text,
    UUID,
    UniqueConstraint,
    func,
    metadata,
    text,
)



cypher_query_audits = Table(
    'cypher_query_audits',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('workflow_id', UUID(), ForeignKey('agent_workflows.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('actor', String(100), nullable=False),
    Column('query_hash', String(64), nullable=False),
    Column('params_hash', String(64), nullable=False),
    Column('allowed', Boolean, nullable=False, default=True, index=True),
    Column('reason', Text, nullable=True),
    Column('row_count', Integer, nullable=False, server_default='0'),
    Column('timeout_seconds', Float, nullable=False),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index('idx_cypher_query_audits_program_created', 'program_id', 'created_at'),
    CheckConstraint("actor != ''", name='ck_cypher_query_audits_actor_not_empty'),
    CheckConstraint("query_hash != ''", name='ck_cypher_query_audits_query_hash_not_empty'),
    CheckConstraint("params_hash != ''", name='ck_cypher_query_audits_params_hash_not_empty'),
    CheckConstraint("row_count >= 0", name='ck_cypher_query_audits_row_count_nonnegative'),
    CheckConstraint("timeout_seconds > 0", name='ck_cypher_query_audits_timeout_positive'),
)


graph_fact_batches = Table(
    'graph_fact_batches',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('produced_by', String(150), nullable=False),
    Column('parser_version', String(100), nullable=False),
    Column('dedupe_key', String(300), nullable=True, unique=True),
    Column('facts_json', JSONType(), nullable=False),
    Column('fact_count', Integer, nullable=False),
    Column('status', String(30), nullable=False, server_default='pending', index=True),
    Column('attempts', Integer, nullable=False, server_default='0'),
    Column('available_at', DateTime(timezone=True), nullable=False, server_default=func.now(), index=True),
    Column('locked_by', String(100), nullable=True),
    Column('locked_until', DateTime(timezone=True), nullable=True),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('applied_at', DateTime(timezone=True), nullable=True),
    Column('last_error', Text, nullable=True),
    Index('idx_graph_fact_batches_status_available', 'status', 'available_at'),
    Index('idx_graph_fact_batches_program_created', 'program_id', 'created_at'),
    Index('uq_graph_fact_batches_dedupe_key', 'dedupe_key', unique=True),
    CheckConstraint("produced_by != ''", name='ck_graph_fact_batches_produced_by_not_empty'),
    CheckConstraint("parser_version != ''", name='ck_graph_fact_batches_parser_version_not_empty'),
    CheckConstraint("dedupe_key IS NULL OR dedupe_key != ''", name='ck_graph_fact_batches_dedupe_key_not_empty'),
    CheckConstraint("fact_count > 0", name='ck_graph_fact_batches_fact_count_positive'),
    CheckConstraint("attempts >= 0", name='ck_graph_fact_batches_attempts_nonnegative'),
    CheckConstraint(
        "status IN ('pending', 'locked', 'applied', 'failed', 'dead')",
        name='ck_graph_fact_batches_status_valid',
    ),
)


graph_projection_events = Table(
    'graph_projection_events',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('source_type', String(100), nullable=False),
    Column('source_id', UUID(), nullable=False, index=True),
    Column('event_type', String(150), nullable=False),
    Column('dedupe_key', String(300), nullable=False, unique=True),
    Column('status', String(30), nullable=False, server_default='pending', index=True),
    Column('attempts', Integer, nullable=False, server_default='0'),
    Column('available_at', DateTime(timezone=True), nullable=False, server_default=func.now(), index=True),
    Column('locked_by', String(100), nullable=True),
    Column('locked_until', DateTime(timezone=True), nullable=True),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('processed_at', DateTime(timezone=True), nullable=True),
    Column('last_error', Text, nullable=True),
    Index('idx_graph_projection_events_status_available', 'status', 'available_at'),
    Index('idx_graph_projection_events_source', 'source_type', 'source_id'),
    Index('uq_graph_projection_events_dedupe_key', 'dedupe_key', unique=True),
    CheckConstraint("source_type != ''", name='ck_graph_projection_events_source_type_not_empty'),
    CheckConstraint("event_type != ''", name='ck_graph_projection_events_event_type_not_empty'),
    CheckConstraint("dedupe_key != ''", name='ck_graph_projection_events_dedupe_key_not_empty'),
    CheckConstraint("attempts >= 0", name='ck_graph_projection_events_attempts_nonnegative'),
    CheckConstraint(
        "status IN ('pending', 'locked', 'processed', 'failed', 'dead')",
        name='ck_graph_projection_events_status_valid',
    ),
)


projection_watermarks = Table(
    'projection_watermarks',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('projection_type', String(50), nullable=False),
    Column('projection_name', String(150), nullable=False),
    Column('source_watermark', Text, nullable=False),
    Column('applied_watermark', Text, nullable=True),
    Column('lag_count', Integer, nullable=False, server_default='0'),
    Column('status', String(30), nullable=False, server_default='observed'),
    Column('last_error', Text, nullable=True),
    Column('observed_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('applied_at', DateTime(timezone=True), nullable=True),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint(
        'program_id',
        'projection_type',
        'projection_name',
        name='uq_projection_watermarks_program_projection',
    ),
    Index('idx_projection_watermarks_program_status', 'program_id', 'status'),
    CheckConstraint("projection_type != ''", name='ck_projection_watermarks_type_not_empty'),
    CheckConstraint("projection_name != ''", name='ck_projection_watermarks_name_not_empty'),
    CheckConstraint("source_watermark != ''", name='ck_projection_watermarks_source_not_empty'),
    CheckConstraint("lag_count >= 0", name='ck_projection_watermarks_lag_nonnegative'),
    CheckConstraint(
        "status IN ('observed', 'running', 'ready', 'failed')",
        name='ck_projection_watermarks_status_valid',
    ),
    CheckConstraint(
        "status != 'ready' OR (lag_count = 0 AND source_watermark = applied_watermark)",
        name='ck_projection_watermarks_ready_consistent',
    ),
)
