"""Campaign, approval, policy, and agent orchestration tables."""
import uuid

from .base import (
    ArrayType,
    Boolean,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    JSONType,
    Integer,
    LargeBinary,
    String,
    Table,
    Text,
    UUID,
    UniqueConstraint,
    func,
    metadata,
    text,
)



campaigns = Table(
    'campaigns',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('correlation_id', UUID(), nullable=False, index=True),
    Column('workflow_id', UUID(), nullable=True, index=True),
    Column('status', String(30), nullable=False, default='created', index=True),
    Column('metadata', JSONType(), nullable=False, default=dict),
    Column('max_runs', Integer, nullable=False, default=1000),
    Column('max_targets', Integer, nullable=False, default=100000),
    Column('runs_consumed', Integer, nullable=False, default=0),
    Column('targets_consumed', Integer, nullable=False, default=0),
    Column('token_capacity', Float, nullable=False, default=100.0),
    Column('tokens_available', Float, nullable=False, default=100.0),
    Column('token_refill_per_second', Float, nullable=False, default=1.0),
    Column('tokens_refilled_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index('idx_campaigns_program_status', 'program_id', 'status'),
    CheckConstraint(
        "status IN ('created', 'running', 'expanding', 'waiting_for_projections', 'quiescent', 'closed', 'cancelled', 'failed')",
        name='ck_campaigns_status_valid'
    ),
    CheckConstraint("max_runs > 0", name='ck_campaigns_max_runs_positive'),
    CheckConstraint("max_targets > 0", name='ck_campaigns_max_targets_positive'),
    CheckConstraint("runs_consumed >= 0", name='ck_campaigns_runs_consumed_nonnegative'),
    CheckConstraint("targets_consumed >= 0", name='ck_campaigns_targets_consumed_nonnegative'),
    CheckConstraint("token_capacity > 0", name='ck_campaigns_token_capacity_positive'),
    CheckConstraint(
        "tokens_available >= 0 AND tokens_available <= token_capacity",
        name='ck_campaigns_tokens_available_nonnegative',
    ),
    CheckConstraint(
        "token_refill_per_second > 0",
        name='ck_campaigns_token_refill_positive',
    ),
)


action_requests = Table(
    'action_requests',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('catalog_entry_id', UUID(), ForeignKey('tool_catalog_entries.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('kind', String(50), nullable=False),
    Column('capability_id', String(100), nullable=False, index=True),
    Column('profile_id', String(100), nullable=False, index=True),
    Column('requested_by', String(100), nullable=False),
    Column('workflow_id', UUID(), nullable=True, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('correlation_id', UUID(), nullable=True, index=True),
    Column('catalog_hash', String(64), nullable=True, index=True),
    Column('metadata', JSONType(), nullable=False, default=dict),
    Column('status', String(30), nullable=False, index=True),
    Column('request', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index('idx_action_requests_program_status', 'program_id', 'status'),
    Index('idx_action_requests_campaign_status', 'campaign_id', 'status'),
    CheckConstraint(
        "status IN ('allowed', 'blocked', 'requires_approval', 'queued', 'rejected')",
        name='ck_action_requests_status_valid'
    ),
)


action_request_targets = Table(
    'action_request_targets',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('action_id', UUID(), ForeignKey('action_requests.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('target', Text, nullable=False),
    Column('position', Integer, nullable=False),
    Column('status', String(30), nullable=False, default='requested', index=True),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('action_id', 'position', name='uq_action_request_targets_action_position'),
    Index('idx_action_request_targets_action_status', 'action_id', 'status'),
    CheckConstraint("target != ''", name='ck_action_request_targets_not_empty'),
    CheckConstraint("position >= 0", name='ck_action_request_targets_position_nonnegative'),
    CheckConstraint("status IN ('requested', 'allowed', 'blocked')", name='ck_action_request_targets_status_valid'),
)


action_request_options = Table(
    'action_request_options',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('action_id', UUID(), ForeignKey('action_requests.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('option_key', String(200), nullable=False),
    Column('option_value', JSONType(), nullable=False),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('action_id', 'option_key', name='uq_action_request_options_action_key'),
    CheckConstraint("option_key != ''", name='ck_action_request_options_key_not_empty'),
)


scope_decisions = Table(
    'scope_decisions',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('action_id', UUID(), ForeignKey('action_requests.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('status', String(30), nullable=False, index=True),
    Column('scope_policy', String(50), nullable=True),
    Column('reasons', JSONType(), nullable=False, default=list),
    Column('allowed_targets', JSONType(), nullable=False, default=list),
    Column('blocked_targets', JSONType(), nullable=False, default=list),
    Column('metadata', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index('idx_scope_decisions_action_status', 'action_id', 'status'),
    CheckConstraint("status IN ('allowed', 'blocked', 'partial', 'not_evaluated')", name='ck_scope_decisions_status_valid'),
)


approval_requests = Table(
    'approval_requests',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('action_id', UUID(), ForeignKey('action_requests.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('policy_decision_id', UUID(), ForeignKey('policy_decisions.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('status', String(30), nullable=False, default='pending', index=True),
    Column('reason', Text, nullable=True),
    Column('requested_by', String(100), nullable=False, default='policy'),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('decided_at', DateTime(timezone=True), nullable=True),
    Index('idx_approval_requests_action_status', 'action_id', 'status'),
    CheckConstraint("status IN ('pending', 'approved', 'rejected', 'cancelled')", name='ck_approval_requests_status_valid'),
)


approval_decisions = Table(
    'approval_decisions',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('approval_request_id', UUID(), ForeignKey('approval_requests.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('action_id', UUID(), ForeignKey('action_requests.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('decision', String(30), nullable=False, index=True),
    Column('decided_by', String(100), nullable=False),
    Column('reason', Text, nullable=True),
    Column('metadata', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    CheckConstraint("decision IN ('approved', 'rejected')", name='ck_approval_decisions_valid'),
)


policy_decisions = Table(
    'policy_decisions',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('action_id', UUID(), ForeignKey('action_requests.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('status', String(30), nullable=False, index=True),
    Column('reasons', JSONType(), nullable=False, default=list),
    Column('allowed_targets', JSONType(), nullable=False, default=list),
    Column('blocked_targets', JSONType(), nullable=False, default=list),
    Column('safety_level', String(30), nullable=True, index=True),
    Column('metadata', JSONType(), nullable=False, default=dict),
    Column('catalog_hash', String(64), nullable=True, index=True),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    CheckConstraint(
        "status IN ('allowed', 'blocked', 'requires_approval', 'rejected')",
        name='ck_policy_decisions_status_valid'
    ),
)


agent_tasks = Table(
    'agent_tasks',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('correlation_id', UUID(), nullable=False, index=True),
    Column('status', String(30), nullable=False, server_default='queued', index=True),
    Column('target_agent', String(100), nullable=False, index=True),
    Column('title', String(200), nullable=False),
    Column('prompt_excerpt', Text, nullable=False),
    Column('prompt_hash', String(64), nullable=False),
    Column('created_by', String(150), nullable=False),
    Column('source', String(100), nullable=False, server_default='ui'),
    Column('context_refs', JSONType(), nullable=False, default=list),
    Column('metadata', JSONType(), nullable=False, default=dict),
    Column('inbox_message_id', UUID(), ForeignKey('agent_inbox.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index('idx_agent_tasks_program_status_created', 'program_id', 'status', 'created_at'),
    Index('idx_agent_tasks_campaign_status_created', 'campaign_id', 'status', 'created_at'),
    Index('idx_agent_tasks_prompt_hash', 'program_id', 'prompt_hash'),
    CheckConstraint(
        "status IN ('queued', 'claimed', 'waiting', 'completed', 'failed', 'cancelled')",
        name='ck_agent_tasks_status_valid',
    ),
    CheckConstraint("target_agent != ''", name='ck_agent_tasks_target_agent_not_empty'),
    CheckConstraint("title != ''", name='ck_agent_tasks_title_not_empty'),
    CheckConstraint("prompt_excerpt != ''", name='ck_agent_tasks_prompt_not_empty'),
    CheckConstraint("prompt_hash != ''", name='ck_agent_tasks_prompt_hash_not_empty'),
    CheckConstraint("created_by != ''", name='ck_agent_tasks_created_by_not_empty'),
    CheckConstraint("source != ''", name='ck_agent_tasks_source_not_empty'),
)


agent_runtime_usage_daily = Table(
    'agent_runtime_usage_daily',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('scope_key', String(320), nullable=False),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('usage_date', Date(), nullable=False, index=True),
    Column('total_agent_messages', Integer, nullable=False, server_default='0'),
    Column('runtime_decision_messages', Integer, nullable=False, server_default='0'),
    Column('requested_none_count', Integer, nullable=False, server_default='0'),
    Column('requested_cheap_count', Integer, nullable=False, server_default='0'),
    Column('requested_normal_count', Integer, nullable=False, server_default='0'),
    Column('requested_deep_count', Integer, nullable=False, server_default='0'),
    Column('selected_none_count', Integer, nullable=False, server_default='0'),
    Column('selected_cheap_count', Integer, nullable=False, server_default='0'),
    Column('selected_normal_count', Integer, nullable=False, server_default='0'),
    Column('selected_deep_count', Integer, nullable=False, server_default='0'),
    Column('llm_allowed_messages', Integer, nullable=False, server_default='0'),
    Column('no_model_messages', Integer, nullable=False, server_default='0'),
    Column('downgraded_messages', Integer, nullable=False, server_default='0'),
    Column('deep_requested_messages', Integer, nullable=False, server_default='0'),
    Column('deep_approved_messages', Integer, nullable=False, server_default='0'),
    Column('deep_downgraded_messages', Integer, nullable=False, server_default='0'),
    Column('context_truncated_messages', Integer, nullable=False, server_default='0'),
    Column('latest_message_id', UUID(), ForeignKey('agent_task_messages.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('latest_selected_mode', String(30), nullable=True),
    Column('latest_requested_mode', String(30), nullable=True),
    Column('latest_reason_code', String(120), nullable=True),
    Column('metadata', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('scope_key', name='uq_agent_runtime_usage_daily_scope_key'),
    Index('idx_agent_runtime_usage_daily_program_date', 'program_id', 'usage_date'),
    Index('idx_agent_runtime_usage_daily_campaign_date', 'campaign_id', 'usage_date'),
    CheckConstraint("scope_key != ''", name='ck_agent_runtime_usage_daily_scope_key_not_empty'),
    CheckConstraint('total_agent_messages >= 0', name='ck_agent_runtime_usage_daily_total_nonnegative'),
    CheckConstraint('runtime_decision_messages >= 0', name='ck_agent_runtime_usage_daily_decisions_nonnegative'),
    CheckConstraint("latest_selected_mode IS NULL OR latest_selected_mode IN ('none', 'cheap', 'normal', 'deep')", name='ck_agent_runtime_usage_daily_latest_selected_valid'),
    CheckConstraint("latest_requested_mode IS NULL OR latest_requested_mode IN ('none', 'cheap', 'normal', 'deep')", name='ck_agent_runtime_usage_daily_latest_requested_valid'),
)


agent_task_messages = Table(
    'agent_task_messages',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('task_id', UUID(), ForeignKey('agent_tasks.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('correlation_id', UUID(), nullable=False, index=True),
    Column('role', String(30), nullable=False),
    Column('message_kind', String(30), nullable=False, server_default='note'),
    Column('agent_key', String(100), nullable=True, index=True),
    Column('body', Text, nullable=False),
    Column('body_hash', String(64), nullable=False),
    Column('artifact_refs', JSONType(), nullable=False, default=list),
    Column('fact_refs', JSONType(), nullable=False, default=list),
    Column('graph_refs', JSONType(), nullable=False, default=list),
    Column('action_refs', JSONType(), nullable=False, default=list),
    Column('proposal_refs', JSONType(), nullable=False, default=list),
    Column('decision_refs', JSONType(), nullable=False, default=list),
    Column('metadata', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index('idx_agent_task_messages_task_created', 'task_id', 'created_at'),
    Index('idx_agent_task_messages_scope_created', 'program_id', 'campaign_id', 'correlation_id', 'created_at'),
    CheckConstraint("role IN ('user', 'agent', 'system')", name='ck_agent_task_messages_role_valid'),
    CheckConstraint(
        "message_kind IN ('note', 'finding', 'proposal', 'question', 'decision', 'error')",
        name='ck_agent_task_messages_kind_valid',
    ),
    CheckConstraint("body != ''", name='ck_agent_task_messages_body_not_empty'),
    CheckConstraint("body_hash != ''", name='ck_agent_task_messages_body_hash_not_empty'),
)


agent_action_proposals = Table(
    'agent_action_proposals',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('task_id', UUID(), ForeignKey('agent_tasks.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('source_message_id', UUID(), ForeignKey('agent_task_messages.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('agent_key', String(100), nullable=False, index=True),
    Column('proposal_key', String(320), nullable=False),
    Column('proposal_type', String(40), nullable=False, server_default='investigation_task', index=True),
    Column('status', String(30), nullable=False, server_default='pending', index=True),
    Column('title', String(200), nullable=False),
    Column('summary', Text, nullable=False),
    Column('rationale', Text, nullable=False, server_default=''),
    Column('capability_id', String(100), nullable=True, index=True),
    Column('profile_id', String(100), nullable=True, index=True),
    Column('priority', String(30), nullable=False, server_default='medium'),
    Column('risk_level', String(30), nullable=False, server_default='low'),
    Column('expected_gain', Text, nullable=False, server_default=''),
    Column('action_intent', Text, nullable=False, server_default=''),
    Column('action_params', JSONType(), nullable=False, default=dict),
    Column('context_refs', JSONType(), nullable=False, default=list),
    Column('metadata', JSONType(), nullable=False, default=dict),
    Column('produced_by', String(100), nullable=False, server_default='agent-task-runtime'),
    Column('accepted_action_id', UUID(), ForeignKey('action_requests.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('accepted_by', String(150), nullable=True),
    Column('accepted_reason', Text, nullable=True),
    Column('accepted_at', DateTime(timezone=True), nullable=True),
    Column('reviewed_by', String(150), nullable=True),
    Column('review_reason', Text, nullable=True),
    Column('review_feedback', JSONType(), nullable=False, default=dict),
    Column('reviewed_at', DateTime(timezone=True), nullable=True),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('proposal_key', name='uq_agent_action_proposals_key'),
    Index('idx_agent_action_proposals_program_status_created', 'program_id', 'status', 'created_at'),
    Index('idx_agent_action_proposals_task_status_created', 'task_id', 'status', 'created_at'),
    Index('idx_agent_action_proposals_capability_profile', 'capability_id', 'profile_id'),
    Index('idx_agent_action_proposals_reviewed_by', 'reviewed_by'),
    CheckConstraint("agent_key != ''", name='ck_agent_action_proposals_agent_not_empty'),
    CheckConstraint("proposal_key != ''", name='ck_agent_action_proposals_key_not_empty'),
    CheckConstraint(
        "proposal_type IN ('investigation_task', 'tool_action')",
        name='ck_agent_action_proposals_type_valid',
    ),
    CheckConstraint(
        "status IN ('pending', 'accepted', 'rejected', 'suppressed', 'expired')",
        name='ck_agent_action_proposals_status_valid',
    ),
    CheckConstraint("title != ''", name='ck_agent_action_proposals_title_not_empty'),
    CheckConstraint("summary != ''", name='ck_agent_action_proposals_summary_not_empty'),
    CheckConstraint("priority != ''", name='ck_agent_action_proposals_priority_not_empty'),
    CheckConstraint("risk_level != ''", name='ck_agent_action_proposals_risk_not_empty'),
    CheckConstraint("produced_by != ''", name='ck_agent_action_proposals_producer_not_empty'),
    CheckConstraint("reviewed_by IS NULL OR reviewed_by != ''", name='ck_agent_action_proposals_reviewed_by_not_empty'),
)


agent_action_proposal_feedback_events = Table(
    'agent_action_proposal_feedback_events',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('proposal_id', UUID(), ForeignKey('agent_action_proposals.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('task_id', UUID(), ForeignKey('agent_tasks.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('source_message_id', UUID(), ForeignKey('agent_task_messages.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('agent_key', String(100), nullable=False, index=True),
    Column('previous_status', String(30), nullable=False),
    Column('new_status', String(30), nullable=False),
    Column('feedback_type', String(40), nullable=False, index=True),
    Column('actor', String(150), nullable=False, index=True),
    Column('reason', Text, nullable=True),
    Column('confidence', Float, nullable=False, server_default='0.5'),
    Column('feedback_tags', JSONType(), nullable=False, default=list),
    Column('metadata', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index('idx_agent_action_proposal_feedback_program_created', 'program_id', 'created_at'),
    Index('idx_agent_action_proposal_feedback_task_created', 'task_id', 'created_at'),
    CheckConstraint("agent_key != ''", name='ck_agent_action_proposal_feedback_agent_not_empty'),
    CheckConstraint("actor != ''", name='ck_agent_action_proposal_feedback_actor_not_empty'),
    CheckConstraint("feedback_type IN ('rejected', 'suppressed')", name='ck_agent_action_proposal_feedback_type_valid'),
    CheckConstraint("new_status IN ('rejected', 'suppressed')", name='ck_agent_action_proposal_feedback_new_status_valid'),
    CheckConstraint("confidence >= 0 AND confidence <= 1", name='ck_agent_action_proposal_feedback_confidence_range'),
)


agent_workflows = Table(
    'agent_workflows',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('correlation_id', UUID(), nullable=False, index=True),
    Column('workflow_type', String(100), nullable=False),
    Column('status', String(30), nullable=False, server_default='created', index=True),
    Column('metadata', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index('idx_agent_workflows_program_status', 'program_id', 'status'),
    Index('idx_agent_workflows_scope', 'program_id', 'campaign_id', 'correlation_id'),
    CheckConstraint("workflow_type != ''", name='ck_agent_workflows_type_not_empty'),
    CheckConstraint(
        "status IN ('created', 'running', 'waiting', 'completed', 'failed', 'cancelled')",
        name='ck_agent_workflows_status_valid',
    ),
)


agent_workflow_runs = Table(
    'agent_workflow_runs',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('workflow_id', UUID(), ForeignKey('agent_workflows.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('correlation_id', UUID(), nullable=False, index=True),
    Column('status', String(30), nullable=False, server_default='queued', index=True),
    Column('current_node', String(150), nullable=True),
    Column('checkpoint_ref', Text, nullable=True),
    Column('metadata', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('started_at', DateTime(timezone=True), nullable=True),
    Column('finished_at', DateTime(timezone=True), nullable=True),
    Index('idx_agent_workflow_runs_workflow_status', 'workflow_id', 'status'),
    Index('idx_agent_workflow_runs_scope', 'program_id', 'campaign_id', 'correlation_id'),
    CheckConstraint(
        "status IN ('queued', 'running', 'waiting', 'completed', 'failed', 'cancelled')",
        name='ck_agent_workflow_runs_status_valid',
    ),
    CheckConstraint(
        "current_node IS NULL OR current_node != ''",
        name='ck_agent_workflow_runs_current_node_not_empty',
    ),
)


agent_subscriptions = Table(
    'agent_subscriptions',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('workflow_id', UUID(), ForeignKey('agent_workflows.id', ondelete='CASCADE'), nullable=True, index=True),
    Column('workflow_run_id', UUID(), ForeignKey('agent_workflow_runs.id', ondelete='CASCADE'), nullable=True, index=True),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('correlation_id', UUID(), nullable=True, index=True),
    Column('event_type', String(150), nullable=False),
    Column('inbox_key', String(200), nullable=False),
    Column('dedupe_key', String(300), nullable=False),
    Column('status', String(30), nullable=False, server_default='active', index=True),
    Column('metadata', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('dedupe_key', name='uq_agent_subscriptions_dedupe_key'),
    Index(
        'idx_agent_subscriptions_scope_event_status',
        'program_id',
        'campaign_id',
        'correlation_id',
        'event_type',
        'status',
    ),
    CheckConstraint("event_type != ''", name='ck_agent_subscriptions_event_type_not_empty'),
    CheckConstraint("inbox_key != ''", name='ck_agent_subscriptions_inbox_key_not_empty'),
    CheckConstraint("dedupe_key != ''", name='ck_agent_subscriptions_dedupe_key_not_empty'),
    CheckConstraint(
        "status IN ('active', 'paused', 'cancelled')",
        name='ck_agent_subscriptions_status_valid',
    ),
)


agent_inbox = Table(
    'agent_inbox',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('subscription_id', UUID(), ForeignKey('agent_subscriptions.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('workflow_id', UUID(), ForeignKey('agent_workflows.id', ondelete='CASCADE'), nullable=True, index=True),
    Column('workflow_run_id', UUID(), ForeignKey('agent_workflow_runs.id', ondelete='CASCADE'), nullable=True, index=True),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('correlation_id', UUID(), nullable=True, index=True),
    Column('event_id', UUID(), ForeignKey('event_store.event_id', ondelete='SET NULL'), nullable=True, index=True),
    Column('message_type', String(150), nullable=False),
    Column('payload', JSONType(), nullable=False, default=dict),
    Column('dedupe_key', String(300), nullable=False),
    Column('status', String(30), nullable=False, server_default='pending', index=True),
    Column('attempts', Integer, nullable=False, server_default='0'),
    Column('available_at', DateTime(timezone=True), nullable=False, server_default=func.now(), index=True),
    Column('locked_by', String(100), nullable=True),
    Column('locked_until', DateTime(timezone=True), nullable=True),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('processed_at', DateTime(timezone=True), nullable=True),
    Column('last_error', Text, nullable=True),
    UniqueConstraint('dedupe_key', name='uq_agent_inbox_dedupe_key'),
    Index('idx_agent_inbox_status_available', 'status', 'available_at'),
    Index('idx_agent_inbox_scope_status', 'program_id', 'campaign_id', 'correlation_id', 'status'),
    CheckConstraint("message_type != ''", name='ck_agent_inbox_message_type_not_empty'),
    CheckConstraint("dedupe_key != ''", name='ck_agent_inbox_dedupe_key_not_empty'),
    CheckConstraint("attempts >= 0", name='ck_agent_inbox_attempts_nonnegative'),
    CheckConstraint(
        "status IN ('pending', 'claimed', 'processed', 'failed', 'dead', 'cancelled')",
        name='ck_agent_inbox_status_valid',
    ),
)


agent_wait_conditions = Table(
    'agent_wait_conditions',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('workflow_run_id', UUID(), ForeignKey('agent_workflow_runs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('correlation_id', UUID(), nullable=True, index=True),
    Column('condition_type', String(50), nullable=False),
    Column('condition_key', String(300), nullable=False),
    Column('status', String(30), nullable=False, server_default='pending', index=True),
    Column('required_state', JSONType(), nullable=False, default=dict),
    Column('resolved_payload', JSONType(), nullable=True),
    Column('deadline_at', DateTime(timezone=True), nullable=True, index=True),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('resolved_at', DateTime(timezone=True), nullable=True),
    UniqueConstraint('workflow_run_id', 'condition_key', name='uq_agent_wait_conditions_run_key'),
    Index('idx_agent_wait_conditions_status_deadline', 'status', 'deadline_at'),
    Index('idx_agent_wait_conditions_scope_type', 'program_id', 'campaign_id', 'correlation_id', 'condition_type'),
    CheckConstraint("condition_key != ''", name='ck_agent_wait_conditions_key_not_empty'),
    CheckConstraint(
        "condition_type IN ('tool_run_completed', 'ingestion_completed', 'projections_ready', 'new_facts_available', 'campaign_quiescent')",
        name='ck_agent_wait_conditions_type_valid',
    ),
    CheckConstraint(
        "status IN ('pending', 'resolved', 'timed_out', 'cancelled')",
        name='ck_agent_wait_conditions_status_valid',
    ),
)


agent_result_sets = Table(
    'agent_result_sets',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('workflow_id', UUID(), ForeignKey('agent_workflows.id', ondelete='CASCADE'), nullable=True, index=True),
    Column('workflow_run_id', UUID(), ForeignKey('agent_workflow_runs.id', ondelete='CASCADE'), nullable=True, index=True),
    Column('action_id', UUID(), ForeignKey('action_requests.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('campaign_id', UUID(), ForeignKey('campaigns.id', ondelete='SET NULL'), nullable=True, index=True),
    Column('correlation_id', UUID(), nullable=True, index=True),
    Column('result_type', String(100), nullable=False),
    Column('result_key', String(300), nullable=False),
    Column('payload', JSONType(), nullable=False, default=dict),
    Column('artifact_refs', JSONType(), nullable=False, default=list),
    Column('fact_refs', JSONType(), nullable=False, default=list),
    Column('search_refs', JSONType(), nullable=False, default=list),
    Column('graph_refs', JSONType(), nullable=False, default=list),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('program_id', 'result_key', name='uq_agent_result_sets_program_key'),
    Index('idx_agent_result_sets_scope_type', 'program_id', 'campaign_id', 'correlation_id', 'result_type'),
    CheckConstraint("result_type != ''", name='ck_agent_result_sets_type_not_empty'),
    CheckConstraint("result_key != ''", name='ck_agent_result_sets_key_not_empty'),
)
