"""Surface map and component analysis read-model tables."""
import uuid

from .base import (
    ArrayType,
    Boolean,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    JSONType,
    Integer,
    LargeBinary,
    String,
    Table,
    Text,
    UUID,
    UniqueConstraint,
    func,
    metadata,
    text,
)



surface_snapshots = Table(
    'surface_snapshots',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('snapshot_fingerprint', String(64), nullable=False),
    Column('algorithm', String(100), nullable=False),
    Column('algorithm_version', String(100), nullable=False),
    Column('source_window_start', DateTime(timezone=True), nullable=True),
    Column('source_window_end', DateTime(timezone=True), nullable=True),
    Column('input_watermark', Text, nullable=True),
    Column('stats_json', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('program_id', 'snapshot_fingerprint', name='uq_surface_snapshots_program_fingerprint'),
    Index('idx_surface_snapshots_program_created', 'program_id', 'created_at'),
    CheckConstraint("snapshot_fingerprint != ''", name='ck_surface_snapshots_fingerprint_not_empty'),
    CheckConstraint("algorithm != ''", name='ck_surface_snapshots_algorithm_not_empty'),
    CheckConstraint("algorithm_version != ''", name='ck_surface_snapshots_algorithm_version_not_empty'),
)


surface_nodes = Table(
    'surface_nodes',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('snapshot_id', UUID(), ForeignKey('surface_snapshots.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('node_type', String(50), nullable=False, index=True),
    Column('ref_type', String(50), nullable=True),
    Column('ref_id', Text, nullable=True),
    Column('node_fingerprint', String(64), nullable=False),
    Column('feature_fingerprint', String(64), nullable=False, index=True),
    Column('feature_version', String(100), nullable=False),
    Column('host', Text, nullable=True),
    Column('path', Text, nullable=True),
    Column('route_template', Text, nullable=True),
    Column('method', String(10), nullable=True),
    Column('status_code', Integer, nullable=True),
    Column('content_type', Text, nullable=True),
    Column('features_json', JSONType(), nullable=False, default=dict),
    Column('safe_for_search', Boolean, nullable=False),
    Column('first_seen', DateTime(timezone=True), nullable=True),
    Column('last_seen', DateTime(timezone=True), nullable=True),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('program_id', 'snapshot_id', 'node_fingerprint', name='uq_surface_nodes_snapshot_fingerprint'),
    Index('idx_surface_nodes_program_snapshot_type', 'program_id', 'snapshot_id', 'node_type'),
    Index('idx_surface_nodes_program_host', 'program_id', 'host'),
    Index('idx_surface_nodes_program_route', 'program_id', 'route_template'),
    CheckConstraint("node_type != ''", name='ck_surface_nodes_node_type_not_empty'),
    CheckConstraint("node_fingerprint != ''", name='ck_surface_nodes_fingerprint_not_empty'),
    CheckConstraint("feature_fingerprint != ''", name='ck_surface_nodes_feature_fingerprint_not_empty'),
    CheckConstraint("feature_version != ''", name='ck_surface_nodes_feature_version_not_empty'),
    CheckConstraint("ref_type IS NULL OR ref_type != ''", name='ck_surface_nodes_ref_type_not_empty'),
    CheckConstraint("ref_id IS NULL OR ref_id != ''", name='ck_surface_nodes_ref_id_not_empty'),
    CheckConstraint(
        "status_code IS NULL OR (status_code >= 100 AND status_code <= 599)",
        name='ck_surface_nodes_status_code_range',
    ),
    CheckConstraint(
        "last_seen IS NULL OR first_seen IS NULL OR last_seen >= first_seen",
        name='ck_surface_nodes_seen_range',
    ),
)


surface_edges = Table(
    'surface_edges',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('snapshot_id', UUID(), ForeignKey('surface_snapshots.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('src_node_id', UUID(), ForeignKey('surface_nodes.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('dst_node_id', UUID(), ForeignKey('surface_nodes.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('edge_type', String(80), nullable=False, index=True),
    Column('weight', Float, nullable=False),
    Column('edge_fingerprint', String(64), nullable=False),
    Column('algorithm_version', String(100), nullable=False),
    Column('evidence_json', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('program_id', 'snapshot_id', 'edge_fingerprint', name='uq_surface_edges_snapshot_fingerprint'),
    Index('idx_surface_edges_program_snapshot_type', 'program_id', 'snapshot_id', 'edge_type'),
    CheckConstraint("edge_type != ''", name='ck_surface_edges_type_not_empty'),
    CheckConstraint("edge_fingerprint != ''", name='ck_surface_edges_fingerprint_not_empty'),
    CheckConstraint("algorithm_version != ''", name='ck_surface_edges_algorithm_version_not_empty'),
    CheckConstraint("weight > 0 AND weight <= 1", name='ck_surface_edges_weight_range'),
    CheckConstraint("src_node_id != dst_node_id", name='ck_surface_edges_no_self_edge'),
)


surface_clusters = Table(
    'surface_clusters',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('snapshot_id', UUID(), ForeignKey('surface_snapshots.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('cluster_fingerprint', String(64), nullable=False),
    Column('algorithm', String(100), nullable=False),
    Column('algorithm_version', String(100), nullable=False),
    Column('member_count', Integer, nullable=False),
    Column('score_json', JSONType(), nullable=False, default=dict),
    Column('summary_json', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('program_id', 'snapshot_id', 'cluster_fingerprint', name='uq_surface_clusters_snapshot_fingerprint'),
    Index('idx_surface_clusters_program_snapshot', 'program_id', 'snapshot_id'),
    CheckConstraint("cluster_fingerprint != ''", name='ck_surface_clusters_fingerprint_not_empty'),
    CheckConstraint("algorithm != ''", name='ck_surface_clusters_algorithm_not_empty'),
    CheckConstraint("algorithm_version != ''", name='ck_surface_clusters_algorithm_version_not_empty'),
    CheckConstraint("member_count >= 0", name='ck_surface_clusters_member_count_non_negative'),
)


surface_cluster_members = Table(
    'surface_cluster_members',
    metadata,
    Column('cluster_id', UUID(), ForeignKey('surface_clusters.id', ondelete='CASCADE'), primary_key=True),
    Column('node_id', UUID(), ForeignKey('surface_nodes.id', ondelete='CASCADE'), primary_key=True),
    Column('role', String(50), nullable=False),
    Column('weight', Float, nullable=False),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Index('ix_surface_cluster_members_cluster_id', 'cluster_id'),
    Index('ix_surface_cluster_members_node_id', 'node_id'),
    CheckConstraint("role != ''", name='ck_surface_cluster_members_role_not_empty'),
    CheckConstraint("weight > 0 AND weight <= 1", name='ck_surface_cluster_members_weight_range'),
)


surface_cluster_labels = Table(
    'surface_cluster_labels',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('cluster_id', UUID(), ForeignKey('surface_clusters.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('label', String(200), nullable=False, index=True),
    Column('label_source', String(50), nullable=False),
    Column('confidence', Float, nullable=False),
    Column('explanation', Text, nullable=True),
    Column('risk_tags_json', JSONType(), nullable=False, default=list),
    Column('evidence_refs', JSONType(), nullable=False, default=list),
    Column('model_version', String(100), nullable=True),
    Column('status', String(30), nullable=False, index=True),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('cluster_id', 'label', 'label_source', name='uq_surface_cluster_labels_cluster_label_source'),
    CheckConstraint("label != ''", name='ck_surface_cluster_labels_label_not_empty'),
    CheckConstraint("label_source != ''", name='ck_surface_cluster_labels_source_not_empty'),
    CheckConstraint("confidence >= 0 AND confidence <= 1", name='ck_surface_cluster_labels_confidence_range'),
    CheckConstraint(
        "status IN ('proposed', 'confirmed', 'rejected', 'merged', 'stale')",
        name='ck_surface_cluster_labels_status_valid',
    ),
    CheckConstraint(
        "label_source IN ('fixture', 'llm', 'manual', 'system')",
        name='ck_surface_cluster_labels_source_valid',
    ),
)


surface_deltas = Table(
    'surface_deltas',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('from_snapshot_id', UUID(), ForeignKey('surface_snapshots.id', ondelete='CASCADE'), nullable=True, index=True),
    Column('to_snapshot_id', UUID(), ForeignKey('surface_snapshots.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('delta_type', String(100), nullable=False, index=True),
    Column('subject_type', String(50), nullable=False),
    Column('subject_fingerprint', String(64), nullable=False),
    Column('novelty_score', Integer, nullable=False),
    Column('details_json', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('program_id', 'to_snapshot_id', 'delta_type', 'subject_fingerprint', name='uq_surface_deltas_snapshot_type_subject'),
    Index('idx_surface_deltas_program_to_snapshot', 'program_id', 'to_snapshot_id'),
    CheckConstraint("delta_type != ''", name='ck_surface_deltas_type_not_empty'),
    CheckConstraint("subject_type != ''", name='ck_surface_deltas_subject_type_not_empty'),
    CheckConstraint("subject_fingerprint != ''", name='ck_surface_deltas_subject_fingerprint_not_empty'),
    CheckConstraint("novelty_score >= 0 AND novelty_score <= 100", name='ck_surface_deltas_novelty_score_range'),
    CheckConstraint(
        "from_snapshot_id IS NULL OR from_snapshot_id != to_snapshot_id",
        name='ck_surface_deltas_distinct_snapshots',
    ),
)


surface_component_analysis_runs = Table(
    'surface_component_analysis_runs',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('snapshot_id', UUID(), ForeignKey('surface_snapshots.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('previous_snapshot_id', UUID(), ForeignKey('surface_snapshots.id', ondelete='SET NULL'), nullable=True),
    Column('algorithm', String(100), nullable=False),
    Column('algorithm_version', String(100), nullable=False),
    Column('report_fingerprint', String(64), nullable=False),
    Column('settings_json', JSONType(), nullable=False, default=dict),
    Column('stats_json', JSONType(), nullable=False, default=dict),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('program_id', 'report_fingerprint', name='uq_surface_component_analysis_runs_program_fingerprint'),
    Index('idx_surface_component_analysis_runs_program_snapshot', 'program_id', 'snapshot_id', 'created_at'),
    CheckConstraint("algorithm != ''", name='ck_surface_component_analysis_runs_algorithm_not_empty'),
    CheckConstraint(
        "algorithm_version != ''",
        name='ck_surface_component_analysis_runs_algorithm_version_not_empty',
    ),
    CheckConstraint("report_fingerprint != ''", name='ck_surface_component_analysis_runs_fingerprint_not_empty'),
)


surface_component_analysis_items = Table(
    'surface_component_analysis_items',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('analysis_run_id', UUID(), ForeignKey('surface_component_analysis_runs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('snapshot_id', UUID(), ForeignKey('surface_snapshots.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('component_id', Integer, nullable=False),
    Column('node_count', Integer, nullable=False),
    Column('changed_node_count', Integer, nullable=False),
    Column('structural_pressure_score', Integer, nullable=True),
    Column('drift_score', Integer, nullable=True),
    Column('bridge_pressure_score', Integer, nullable=True),
    Column('outlier_score', Integer, nullable=True),
    Column('coverage_score', Integer, nullable=True),
    Column('exploration_priority_score', Integer, nullable=True),
    Column('action_candidate_count', Integer, nullable=False),
    Column('metrics_json', JSONType(), nullable=False, default=dict),
    Column('action_candidates_json', JSONType(), nullable=False, default=list),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint('analysis_run_id', 'component_id', name='uq_surface_component_analysis_items_run_component'),
    Index('idx_surface_component_analysis_items_priority', 'snapshot_id', 'exploration_priority_score', 'structural_pressure_score'),
    CheckConstraint("component_id >= 0", name='ck_surface_component_analysis_items_component_non_negative'),
    CheckConstraint("node_count >= 0", name='ck_surface_component_analysis_items_node_count_non_negative'),
    CheckConstraint("changed_node_count >= 0", name='ck_surface_component_analysis_items_changed_count_non_negative'),
    CheckConstraint("action_candidate_count >= 0", name='ck_surface_component_analysis_items_candidate_count_nonneg'),
    CheckConstraint(
        "structural_pressure_score IS NULL OR (structural_pressure_score >= 0 AND structural_pressure_score <= 100)",
        name='ck_surface_component_analysis_items_structural_score_range',
    ),
    CheckConstraint(
        "drift_score IS NULL OR (drift_score >= 0 AND drift_score <= 100)",
        name='ck_surface_component_analysis_items_drift_score_range',
    ),
    CheckConstraint(
        "bridge_pressure_score IS NULL OR (bridge_pressure_score >= 0 AND bridge_pressure_score <= 100)",
        name='ck_surface_component_analysis_items_bridge_score_range',
    ),
    CheckConstraint(
        "outlier_score IS NULL OR (outlier_score >= 0 AND outlier_score <= 100)",
        name='ck_surface_component_analysis_items_outlier_score_range',
    ),
    CheckConstraint(
        "coverage_score IS NULL OR (coverage_score >= 0 AND coverage_score <= 100)",
        name='ck_surface_component_analysis_items_coverage_score_range',
    ),
    CheckConstraint(
        "exploration_priority_score IS NULL OR (exploration_priority_score >= 0 AND exploration_priority_score <= 100)",
        name='ck_surface_component_analysis_items_exploration_score_range',
    ),
)


surface_component_analysis_events = Table(
    'surface_component_analysis_events',
    metadata,
    Column('id', UUID(), primary_key=True, default=uuid.uuid4),
    Column('program_id', UUID(), ForeignKey('programs.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('snapshot_id', UUID(), ForeignKey('surface_snapshots.id', ondelete='CASCADE'), nullable=False, index=True),
    Column('previous_snapshot_id', UUID(), ForeignKey('surface_snapshots.id', ondelete='SET NULL'), nullable=True),
    Column('event_type', String(100), nullable=False),
    Column('analysis_version', String(100), nullable=False),
    Column('dedupe_key', String(300), nullable=False),
    Column('settings_json', JSONType(), nullable=False, default=dict, server_default=text("'{}'")),
    Column('result_json', JSONType(), nullable=True),
    Column('status', String(30), nullable=False, server_default='pending', index=True),
    Column('attempts', Integer, nullable=False, server_default='0'),
    Column('available_at', DateTime(timezone=True), nullable=False, server_default=func.now(), index=True),
    Column('locked_by', String(100), nullable=True),
    Column('locked_until', DateTime(timezone=True), nullable=True),
    Column('created_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('updated_at', DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column('processed_at', DateTime(timezone=True), nullable=True),
    Column('last_error', Text, nullable=True),
    Index('idx_surface_component_analysis_events_status_available', 'status', 'available_at'),
    Index('uq_surface_component_analysis_events_dedupe_key', 'dedupe_key', unique=True),
    CheckConstraint("event_type != ''", name='ck_surface_component_analysis_events_type_not_empty'),
    CheckConstraint("analysis_version != ''", name='ck_surface_component_analysis_events_version_not_empty'),
    CheckConstraint("dedupe_key != ''", name='ck_surface_component_analysis_events_dedupe_not_empty'),
    CheckConstraint("attempts >= 0", name='ck_surface_component_analysis_events_attempts_nonnegative'),
    CheckConstraint(
        "status IN ('pending', 'locked', 'processed', 'failed', 'dead')",
        name='ck_surface_component_analysis_events_status_valid',
    ),
)
