import { 
  Search, Globe, Database, Network, FileCode, Bug, Shield 
} from 'lucide-react'
import { 
  runSubfinder, runHTTPX, runGAU, runWaymore, runKatana,
  runPlaywright, runLinkFinder, runMantra, runFFUF, runAmass, runDNSx,
  runSubjack, runASNMap, runMapCIDR, runNaabu
} from '@/services/api'

export const ACTIONS = [
  {
    id: 'subfinder',
    name: 'Subfinder',
    description: 'Subdomain enumeration',
    icon: Search,
    color: 'blue',
    api: runSubfinder,
    form: 'Subfinder',
    initialValues: { targets: '', probe: true, timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'probe', label: 'Probe', type: 'checkbox' },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'httpx',
    name: 'HTTPX',
    description: 'HTTP probing',
    icon: Globe,
    color: 'green',
    api: runHTTPX,
    form: 'HTTPX',
    initialValues: { targets: '', timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'gau',
    name: 'GAU',
    description: 'URL discovery from web archives',
    icon: Database,
    color: 'purple',
    api: runGAU,
    form: 'GAU',
    initialValues: { targets: '', include_subs: true, timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'include_subs', label: 'Include Subdomains', type: 'checkbox' },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'waymore',
    name: 'Waymore',
    description: 'URL discovery from multiple sources',
    icon: Search,
    color: 'indigo',
    api: runWaymore,
    form: 'Waymore',
    initialValues: { targets: '', timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'katana',
    name: 'Katana',
    description: 'Web crawling',
    icon: Network,
    color: 'red',
    api: runKatana,
    form: 'Katana',
    initialValues: { targets: '', depth: 3, js_crawl: true, headless: false, timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'depth', label: 'Depth (1-10)', type: 'number', min: 1, max: 10 },
      { name: 'js_crawl', label: 'JS Crawl', type: 'checkbox' },
      { name: 'headless', label: 'Headless', type: 'checkbox' },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'playwright',
    name: 'Playwright',
    description: 'Interactive browser-based crawling',
    icon: Globe,
    color: 'pink',
    api: runPlaywright,
    form: 'Playwright',
    initialValues: { targets: '', depth: 3, js_crawl: true, headless: false, timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'depth', label: 'Depth (1-10)', type: 'number', min: 1, max: 10 },
      { name: 'js_crawl', label: 'JS Crawl', type: 'checkbox' },
      { name: 'headless', label: 'Headless', type: 'checkbox' },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'linkfinder',
    name: 'LinkFinder',
    description: 'JS analysis for hidden endpoints',
    icon: FileCode,
    color: 'yellow',
    api: runLinkFinder,
    form: 'LinkFinder',
    initialValues: { targets: '', timeout: 15 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 60 },
    ],
  },
  {
    id: 'mantra',
    name: 'Mantra',
    description: 'Secret scanning on JavaScript files',
    icon: Shield,
    color: 'orange',
    api: runMantra,
    form: 'Mantra',
    initialValues: { targets: '', timeout: 300 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'ffuf',
    name: 'FFUF',
    description: 'Directory/file fuzzing',
    icon: Bug,
    color: 'cyan',
    api: runFFUF,
    form: 'FFUF',
    initialValues: { targets: '', timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'dnsx',
    name: 'DNSx',
    description: 'DNS enumeration',
    icon: Network,
    color: 'teal',
    api: runDNSx,
    form: 'DNSx',
    initialValues: { targets: '', mode: 'basic', timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'mode', label: 'Mode', type: 'select', options: ['basic', 'deep', 'ptr'] },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'subjack',
    name: 'Subjack',
    description: 'Subdomain takeover detection',
    icon: Shield,
    color: 'rose',
    api: runSubjack,
    form: 'Subjack',
    initialValues: { targets: '', timeout: 300 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'asnmap',
    name: 'ASNMap',
    description: 'ASN/CIDR enumeration',
    icon: Network,
    color: 'violet',
    api: runASNMap,
    form: 'ASNMap',
    initialValues: { targets: '', mode: 'domain', timeout: 300 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'mode', label: 'Mode', type: 'select', options: ['domain', 'asn', 'organization'] },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'mapcidr',
    name: 'MapCIDR',
    description: 'CIDR operations',
    icon: Database,
    color: 'slate',
    api: runMapCIDR,
    form: 'MapCIDR',
    initialValues: { cidrs: '', operation: 'expand', count: '', host_count: '', skip_base: false, skip_broadcast: false, shuffle: false, timeout: 300 },
    fields: [
      { name: 'cidrs', label: 'CIDRs', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'operation', label: 'Operation', type: 'select', options: ['expand', 'slice_count', 'slice_host', 'aggregate'] },
      { name: 'count', label: 'Count (subnets)', type: 'number', min: 1, dependsOn: { field: 'operation', value: 'slice_count' } },
      { name: 'host_count', label: 'Host Count', type: 'number', min: 1, dependsOn: { field: 'operation', value: 'slice_host' } },
      { name: 'skip_base', label: 'Skip Base IPs (.0)', type: 'checkbox' },
      { name: 'skip_broadcast', label: 'Skip Broadcast IPs (.255)', type: 'checkbox' },
      { name: 'shuffle', label: 'Shuffle IPs', type: 'checkbox' },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'naabu',
    name: 'Naabu',
    description: 'Port scanning',
    icon: Network,
    color: 'amber',
    api: runNaabu,
    form: 'Naabu',
    initialValues: { targets: '', scan_mode: 'active', ports: '', top_ports: '1000', rate: 1000, scan_type: 'c', exclude_cdn: true, timeout: 600 },
    fields: [
      { name: 'targets', label: 'Targets', type: 'textarea', placeholder: 'one per line', required: true },
      { name: 'scan_mode', label: 'Scan Mode', type: 'select', options: ['active', 'passive'] },
      { name: 'ports', label: 'Ports', type: 'text', placeholder: '80,443,8080' },
      { name: 'top_ports', label: 'Top Ports', type: 'select', options: ['100', '1000', 'full'], dependsOn: { field: 'ports', value: '' } },
      { name: 'rate', label: 'Rate (pps)', type: 'number', min: 1, max: 10000 },
      { name: 'scan_type', label: 'Scan Type', type: 'select', options: ['s', 'c'] },
      { name: 'exclude_cdn', label: 'Exclude CDN/WAF', type: 'checkbox' },
      { name: 'timeout', label: 'Timeout (seconds)', type: 'number', min: 1, max: 3600 },
    ],
  },
  {
    id: 'amass',
    name: 'Amass',
    description: 'Subdomain enumeration with active mode',
    icon: Search,
    color: 'indigo',
    api: runAmass,
    form: 'Amass',
    initialValues: { targets: '', active: false, timeout: 1800 },
    fields: [
      { 
        name: 'targets', 
        label: 'Domains (one per line)', 
        type: 'textarea', 
        placeholder: 'example.com\napi.example.com\nadmin.example.com', 
        required: true 
      },
      { 
        name: 'active', 
        label: 'Active enumeration', 
        type: 'checkbox',
        description: 'Enable brute force and zone transfers (more aggressive)' 
      },
      { 
        name: 'timeout', 
        label: 'Timeout (seconds)', 
        type: 'number', 
        min: 60, 
        max: 7200,
        description: '30 minutes (1800s) recommended for active scans' 
      },
    ],
  }
]
