from __future__ import annotations

from .projection_contract_models import AlgorithmFamily, ProjectionContract, _contract, _signal


PRIMARY_PROJECTION_CONTRACTS: tuple[ProjectionContract, ...] = (
_contract(
        name="G_asset",
        purpose="Rebuildable asset ownership, infrastructure grouping, service exposure, and coverage reasoning.",
        contract_version="v1",
        source_projections=(),
        input_facts=(
            "canonical domain and subdomain facts",
            "canonical host and IP facts",
            "canonical service observations",
            "canonical technology observations",
            "program scope and ownership metadata",
        ),
        node_types=(
            "organization",
            "domain",
            "subdomain",
            "host",
            "ip",
            "cidr",
            "asn",
            "service",
            "technology",
        ),
        edge_types=(
            "OWNS",
            "HAS_SUBDOMAIN",
            "RESOLVES_TO",
            "IN_CIDR",
            "IN_ASN",
            "EXPOSES_SERVICE",
            "USES_TECHNOLOGY",
        ),
        algorithm_families=(
            AlgorithmFamily.WCC,
            AlgorithmFamily.DEGREE,
            AlgorithmFamily.CENTRALITY,
            AlgorithmFamily.COVERAGE_SUMMARY,
        ),
        allowed_algorithms=(
            "weakly connected components",
            "degree and centrality summaries",
            "same-backend candidate baseline",
            "service co-location summary",
            "host/service coverage summary",
        ),
        output_signals=(
            "AssetComponentSignal",
            "ServiceExposureSignal",
            "HostTechnologyNeighborhoodSignal",
            "AssetCoverageGapSignal",
        ),
        output_signal_families=(
            _signal("AssetComponentSignal", AlgorithmFamily.WCC, AlgorithmFamily.COVERAGE_SUMMARY),
            _signal("ServiceExposureSignal", AlgorithmFamily.DEGREE, AlgorithmFamily.CENTRALITY),
            _signal("HostTechnologyNeighborhoodSignal", AlgorithmFamily.DEGREE, AlgorithmFamily.CENTRALITY),
            _signal("AssetCoverageGapSignal", AlgorithmFamily.COVERAGE_SUMMARY),
        ),
        lineage_requirements=(
            "program_id",
            "source canonical fact ids",
            "projection snapshot id",
            "normalization version",
        ),
        sensitivity_rules=(
            "do not project raw secrets or credential material",
            "scope ownership metadata must remain bounded to the program",
            "private IP and internal host labels require audit-safe rendering",
        ),
        forbidden_interpretations=(
            "service exposure is not a vulnerability verdict",
            "technology presence is not an exploit recommendation",
            "centrality is not permission to run a tool",
        ),
        failure_modes=(
            "DNS churn can create unstable host components",
            "shared hosting can merge unrelated assets",
            "technology fingerprints can be stale or generic",
        ),
    ),
_contract(
        name="G_http",
        purpose="HTTP surface topology, endpoint neighborhoods, response-shape similarity, coverage, and drift over observed routes.",
        contract_version="v1",
        source_projections=(),
        input_facts=(
            "canonical HTTP observations",
            "endpoint normalization facts",
            "route-template normalization facts",
            "parameter observations",
            "response-shape observations",
            "observed action references",
        ),
        node_types=(
            "host",
            "endpoint",
            "route_template",
            "method",
            "param",
            "body_schema",
            "response_shape",
            "status_class",
            "content_type",
            "observed_action",
        ),
        edge_types=(
            "HOSTS_ENDPOINT",
            "HAS_ROUTE_TEMPLATE",
            "USES_METHOD",
            "HAS_PARAM",
            "HAS_BODY_SCHEMA",
            "RETURNS_RESPONSE_SHAPE",
            "RETURNS_STATUS_CLASS",
            "RETURNS_CONTENT_TYPE",
            "OBSERVED_BY_ACTION",
        ),
        algorithm_families=(
            AlgorithmFamily.DEGREE,
            AlgorithmFamily.JACCARD_SIMILARITY,
            AlgorithmFamily.COVERAGE_SUMMARY,
            AlgorithmFamily.DRIFT_SUMMARY,
        ),
        allowed_algorithms=(
            "endpoint degree",
            "endpoint similarity by parameter neighborhood",
            "endpoint similarity by response-shape neighborhood",
            "route-template component coverage",
            "coverage and drift summary",
        ),
        output_signals=(
            "HttpEndpointNeighborhoodSignal",
            "HttpCoverageGapSignal",
            "HttpDriftSignal",
            "HttpMissingRelationCandidateSignal",
        ),
        output_signal_families=(
            _signal("HttpEndpointNeighborhoodSignal", AlgorithmFamily.DEGREE, AlgorithmFamily.JACCARD_SIMILARITY),
            _signal("HttpCoverageGapSignal", AlgorithmFamily.COVERAGE_SUMMARY),
            _signal("HttpDriftSignal", AlgorithmFamily.DRIFT_SUMMARY),
            _signal("HttpMissingRelationCandidateSignal", AlgorithmFamily.JACCARD_SIMILARITY, AlgorithmFamily.COVERAGE_SUMMARY),
        ),
        lineage_requirements=(
            "program_id",
            "HTTP observation ids",
            "endpoint normalization version",
            "projection snapshot id",
            "source action outcome ids where available",
        ),
        sensitivity_rules=(
            "do not project raw headers, cookies, tokens, or request bodies containing secrets",
            "credential refs may be represented only as opaque references when required",
            "query values must be redacted unless explicitly classified safe",
        ),
        forbidden_interpretations=(
            "parameter names are not IDOR findings",
            "admin-looking routes are not admin vulnerability verdicts",
            "JWT observations are not JWT-tamper action engines",
            "missing CSRF-like observations are not findings",
        ),
        failure_modes=(
            "route-template normalization can over-merge endpoints",
            "parameter extraction can under-observe dynamic clients",
            "response-shape similarity can cluster unrelated endpoints",
        ),
    ),
_contract(
        name="G_identity",
        purpose="Auth-context coverage and identity/object relationship reasoning without exposing secrets.",
        contract_version="v1",
        source_projections=(),
        input_facts=(
            "principal observations",
            "role observations",
            "tenant observations",
            "auth context observations",
            "opaque credential refs",
            "object reference observations",
            "observed permission boundary notes",
        ),
        node_types=(
            "principal",
            "role",
            "tenant",
            "auth_context",
            "credential_ref",
            "object_ref",
            "observed_permission_boundary",
        ),
        edge_types=(
            "HAS_ROLE",
            "IN_TENANT",
            "USES_AUTH_CONTEXT",
            "USES_CREDENTIAL_REF",
            "ACCESSED_OBJECT",
            "OBSERVED_BOUNDARY",
        ),
        algorithm_families=(
            AlgorithmFamily.COVERAGE_SUMMARY,
            AlgorithmFamily.REACHABILITY_SUMMARY,
        ),
        allowed_algorithms=(
            "bipartite coverage summary",
            "role/tenant neighborhood comparison",
            "principal-object reachability summary",
            "missing observation suggestion baseline",
        ),
        output_signals=(
            "IdentityCoverageGapSignal",
            "PrincipalObjectNeighborhoodSignal",
            "AuthContextComparisonSignal",
        ),
        output_signal_families=(
            _signal("IdentityCoverageGapSignal", AlgorithmFamily.COVERAGE_SUMMARY),
            _signal("PrincipalObjectNeighborhoodSignal", AlgorithmFamily.REACHABILITY_SUMMARY),
            _signal("AuthContextComparisonSignal", AlgorithmFamily.COVERAGE_SUMMARY),
        ),
        lineage_requirements=(
            "program_id",
            "auth context observation ids",
            "opaque credential_ref ids",
            "source action outcome ids",
            "projection snapshot id",
        ),
        sensitivity_rules=(
            "never project raw secrets, cookies, session material, or Authorization headers",
            "credential refs are opaque identity handles only",
            "tenant/principal labels require audit-safe rendering when sensitive",
        ),
        forbidden_interpretations=(
            "reachability summary is not authorization bypass proof",
            "role similarity is not a privilege escalation verdict",
            "credential_ref presence is not permission to materialize a secret",
        ),
        failure_modes=(
            "principal canonicalization can merge test users incorrectly",
            "tenant observations can be incomplete",
            "object references can be sparse or synthetic",
        ),
    ),
_contract(
        name="G_finding",
        purpose="Evidence lineage, hypothesis-to-evidence traceability, duplicate grouping, and report synthesis.",
        contract_version="v1",
        source_projections=(),
        input_facts=(
            "structural signal records",
            "hypothesis proposal records",
            "evidence references",
            "finding records",
            "root-cause grouping metadata",
            "report section references",
            "action outcome references",
        ),
        node_types=(
            "structural_signal",
            "hypothesis",
            "evidence",
            "finding",
            "root_cause",
            "report_section",
            "action_outcome",
        ),
        edge_types=(
            "PROPOSED_FROM_SIGNAL",
            "SUPPORTED_BY_EVIDENCE",
            "PROMOTED_TO_FINDING",
            "GROUPED_UNDER_ROOT_CAUSE",
            "MENTIONED_IN_REPORT_SECTION",
            "OBSERVED_BY_OUTCOME",
        ),
        algorithm_families=(
            AlgorithmFamily.EVIDENCE_SIMILARITY,
            AlgorithmFamily.DUPLICATE_GROUPING,
            AlgorithmFamily.COVERAGE_SUMMARY,
        ),
        allowed_algorithms=(
            "evidence-neighborhood similarity",
            "duplicate/root-cause candidate grouping",
            "evidence coverage summary",
            "report traversal summary",
        ),
        output_signals=(
            "EvidenceCoverageSignal",
            "DuplicateFindingCandidateSignal",
            "RootCauseGroupingCandidateSignal",
            "ReportTraceabilitySignal",
        ),
        output_signal_families=(
            _signal("EvidenceCoverageSignal", AlgorithmFamily.COVERAGE_SUMMARY),
            _signal("DuplicateFindingCandidateSignal", AlgorithmFamily.EVIDENCE_SIMILARITY, AlgorithmFamily.DUPLICATE_GROUPING),
            _signal("RootCauseGroupingCandidateSignal", AlgorithmFamily.EVIDENCE_SIMILARITY, AlgorithmFamily.DUPLICATE_GROUPING),
            _signal("ReportTraceabilitySignal", AlgorithmFamily.COVERAGE_SUMMARY),
        ),
        lineage_requirements=(
            "program_id",
            "signal ids",
            "hypothesis ids",
            "evidence refs",
            "finding ids when promoted",
            "projection snapshot id",
        ),
        sensitivity_rules=(
            "reportable evidence views must remain redacted when source artifacts contain secrets",
            "finding labels remain annotations and do not drive tool execution",
            "agent-facing projections must use evidence refs rather than raw artifacts",
        ),
        forbidden_interpretations=(
            "duplicate candidate is not a confirmed duplicate",
            "root-cause candidate is not a final report grouping",
            "structural signal is not a finding",
        ),
        failure_modes=(
            "evidence refs can point to stale artifacts",
            "similar symptoms can have different root causes",
            "report grouping can hide distinct reproduction paths",
        ),
    ),
_contract(
        name="G_temporal",
        purpose="Temporal drift, co-change, novelty decay, replay, and before/after explanation.",
        contract_version="v1",
        source_projections=(),
        input_facts=(
            "surface snapshots",
            "surface deltas",
            "stable fingerprints",
            "action windows",
            "observation timestamps",
            "before/after snapshot links",
        ),
        node_types=(
            "snapshot",
            "appeared",
            "disappeared",
            "changed",
            "stable_fingerprint",
            "action_window",
            "observation_time",
        ),
        edge_types=(
            "NEXT_SNAPSHOT",
            "HAS_APPEARED",
            "HAS_DISAPPEARED",
            "HAS_CHANGED",
            "STABLE_AS",
            "DURING_ACTION_WINDOW",
            "OBSERVED_AT",
        ),
        algorithm_families=(
            AlgorithmFamily.DRIFT_SUMMARY,
            AlgorithmFamily.TEMPORAL_CO_CHANGE,
            AlgorithmFamily.NOVELTY_DECAY,
            AlgorithmFamily.COVERAGE_SUMMARY,
        ),
        allowed_algorithms=(
            "component drift summary",
            "co-change grouping",
            "time-window coverage summary",
            "novelty decay ranking",
        ),
        output_signals=(
            "TemporalDriftSignal",
            "CoChangeClusterSignal",
            "NoveltyDecaySignal",
            "ReplayWindowSignal",
        ),
        output_signal_families=(
            _signal("TemporalDriftSignal", AlgorithmFamily.DRIFT_SUMMARY),
            _signal("CoChangeClusterSignal", AlgorithmFamily.TEMPORAL_CO_CHANGE),
            _signal("NoveltyDecaySignal", AlgorithmFamily.NOVELTY_DECAY),
            _signal("ReplayWindowSignal", AlgorithmFamily.COVERAGE_SUMMARY, AlgorithmFamily.DRIFT_SUMMARY),
        ),
        lineage_requirements=(
            "program_id",
            "previous snapshot id",
            "current snapshot id",
            "delta ids",
            "action window ids where available",
        ),
        sensitivity_rules=(
            "time windows must not reveal secret-bearing request content",
            "internal clock skew must be surfaced as uncertainty",
            "before/after views must link to redacted evidence refs",
        ),
        forbidden_interpretations=(
            "novelty is not severity",
            "co-change is not causality",
            "drift is not a bug verdict",
        ),
        failure_modes=(
            "clock skew can distort ordering",
            "snapshot gaps can exaggerate drift",
            "high-churn endpoints can dominate novelty signals",
        ),
    )
)
